### ISSUE TITLE
Unable to select multiple images

### ISSUE THREAD

**Issue by baguosiji** [NativeScript/nativescript-imagepicker#111]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
When I used imagepicker, I just uploaded a picture, now I have the need to upload multiple images, I found {mode:"multiple"} does not work, who can tell me what the reason is?

### Which platform(s) does your issue occur on?
Android
### Please, provide the following version numbers that your issue occurs with:
tns version 3.1.2;
imagepicker version 3.0.6;
### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
This is my code

onSelectSingleTap(data) {
        let context = imagepickerModule.create({
            mode: "multiple"
        });
        if (platformModule.device.os === "Android" && Number(platformModule.device.sdkVersion) >= 23) {
            permissions.requestPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE, "I need these permissions to read from storage")
                .then((response) => {
                    context.authorize()
                        .then(() => {
                            context.present()
                                .then((res) => {
                                    //res[0]._android为找到的当前图像
                                    //构造一个HTTP发送
                                    this.sendImages(null, res[0]._android, data);
                                })
                                .catch((err) => {
                                    viewUtils.toast("没有选择图片");
                                })
                        })
                        .catch(function (e) {
                        });
                })
                .catch(function () {
                });
        } else {
            this.startSelection(context, data);
        }
    }

**Comment by tsonevn** [comment]
Hi @baguosiji,
Thank you for reporting this issue.
I tested this scenario with [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) and the multiple images upload seems to work as expected. 
I am also attaching the project with updated versions of `tns-core-modules` and `nativescript-imagepicker`
Keep in mind that to be able to select more than one image, you should make a long press on the items, which will be uploaded
[Archive.zip](https://github.com/NativeScript/nativescript-imagepicker/files/1337189/Archive.zip)

**Comment by bigradish** [comment]
@tsonevn Are you sure you are using an android mobile phone? The long press does not make multi-selection work on my android mobile phone. Thank you.

**Comment by tsonevn** [comment]
Hi @bigradish,
Indeed, I tested this scenario on Android device. Could you provide more info about your device? Also, it would help if you could prove on another device and check if you can recreate the issue on it.

**Comment by bigradish** [comment]
Hi @tsonevn 
I'm using Huawei Honor mobile phone (the phone comes into the market about 1 - 2 years), and the version of its android is 7.0
The multiple selection function of the picture gallery app in this phone does work: long-press an image, and then the multiple-selection mode emerges.
But the multiple-selection mode of your imagepicker does not work in this phone.
My testing code is just from your sample:

`let context = imagepicker.create({ mode: "multiple" });
context.authorize()
	.then(function() {
			return context.present();
	})
	.then(function(selection) {
			console.log("Selection done:");
	}).catch(function (e) {
			console.log(e);
	});`

I've updated the imagepicker plugin to the newest version, and Nativescript CLI is 3.4.2, Cross-platform modules is of 3.4.0
I don't have another android mobile phone to test, sorry.

**Comment by bigradish** [comment]
@tsonevn Is the android version of your device 7.0?
Huawei mobile phone's market share in the world is not small, and is rising. Hope you can pay more attention to this issue.
Thank you very much.

**Comment by fotoguy42** [comment]
I think the issue with Android intents, is that it lets the user select which image selector they are going to use. On my Galaxy Note 4, Android 6.0.1, if I choose the default Gallery, it does not allow me to multi-select, no matter how long I tap and hold an image, it won't let me multi-select. If I use the Google Photos app as my image selector, then I can multi-select. 
You can test with my nativescript playground project: 
[native script playground example](https://play.nativescript.org/?template=play-tsc&id=OTctTC&v=2)

So, there's nothing wrong with necessarily with this, but what is really needed is a solution that does not rely on another app.

**Comment by bigradish** [comment]
@fotoguy42 You are exactly right!
@tsonevn perhaps Gallery is the most used app on Android platform. How to resolve this issue?

**Comment by fotoguy42** [comment]
If they continue to use another app for the selection, in the android code (I assume there is actual android sdk somewhere in this), they could do something like mentioned in this [SF](https://stackoverflow.com/a/46705590/232226) post. The problem with that is you are still reliant on another app, that may not be installed, for your image selection.

**Comment by bigradish** [comment]
@fotoguy42 I agree. Relying on other apps is not a good idea. I think it should be better for them to use an Android image picker library, such as https://github.com/esafirm/android-image-picker

**Comment by pitamash** [comment]
this.imagePicker.getPictures({
        maximumImagesCount: 10,
        width:512,
        height:512,
        outputType: 1 ,
        quality:45
     }).then((results) => {
       for (var i = 0; i < results.length; i++) {
         if(results[i] ){
           let thisimg = {
               "src":'data:image/jpeg;base64,' + results[i] 
           };
           setTimeout(()=>{
            this.imageLists.push( thisimg );
           },1000) 
           //this.imageLists.reverse();
         } 
       } 
        
    }, (err) => { 
        this.events.publish("toast",err);
    });

**Comment by pitamash** [comment]
Use timeout to push images , I think that sorts out memory issue by pushing the images one by one at an interval 
this.imagePicker.getPictures({
        maximumImagesCount: 10,
        width:512,
        height:512,
        outputType: 1 ,
        quality:45
     }).then((results) => {
       for (var i = 0; i < results.length; i++) {
         if(results[i] ){
           let thisimg = {
               "src":'data:image/jpeg;base64,' + results[i] 
           };
           setTimeout(()=>{
            this.imageLists.push( thisimg );
           },1000) 
           //this.imageLists.reverse();
         } 
       }  
    }, (err) => { 
        this.events.publish("toast",err);
    });

**Comment by pitamash** [comment]
Use timeout to push images , I think that sorts out memory issue by pushing the images one by one at an interval 
```
this.imagePicker.getPictures({
        maximumImagesCount: 10,
        width:512,
        height:512,
        outputType: 1 ,
        quality:45
     }).then((results) => {
       for (var i = 0; i < results.length; i++) {
         if(results[i] ){
           let thisimg = {
               "src":'data:image/jpeg;base64,' + results[i] 
           };
           setTimeout(()=>{
            this.imageLists.push( thisimg );
           },1000) 
           //this.imageLists.reverse();
         } 
       }  
    }, (err) => { 
        this.events.publish("toast",err);
    });
`````
