### ISSUE TITLE
nativescript-pro-ui is required since 3.0.7

### ISSUE THREAD

**Issue by wbancer** [NativeScript/nativescript-imagepicker#115]
Does it mean this plugin is no longer free?

In version 3.0.7 package.json has slightly changed. 

The:
`nativescript-telerik-ui`

has been removed from devDependencies, and:

`nativescript-pro-ui`

has been added to dependencies.

In my case this was causing compilation error, because I don't have non-free nativescript-pro-ui.
Is this intentional? Is this plugin no longer free?

**Comment by abhayastudios** [comment]
@wbancer take the latest version which contains a fix for it already, see #112

**Comment by wbancer** [comment]
Well this #112 is exactly what introduced an issue. 
nativescript-pro-ui is not a free package.

**Comment by abhayastudios** [comment]
@wbancer sorry, I misread... see my updated answer above.

**Comment by wbancer** [comment]
@abhayastudios ok, thank you for you update and clarification. :)

Yes, nativescript-pro-ui informs about trial and LICENCE.md file also contains informations about License seats, so I guess it's not updated either. So it still doesn't look like free product, but I hope they sort this out soon.

**Comment by tgpetrov** [comment]
@wbancer The [nativescript-pro-ui](https://www.npmjs.com/package/nativescript-pro-ui) has been updated and you should no longer see the trial message. [Here](https://github.com/telerik/nativescript-ui-feedback/blob/master/LICENSE.md) you can find the updated license file.
