### ISSUE TITLE
I can't see any image when open my camera roll, I see a white screen

### ISSUE THREAD

**Issue by cpvbruno** [NativeScript/nativescript-imagepicker#116]

**Comment by tsonevn** [comment]
Hi, @cpvbruno,
Could you provide some more info about the problem? It would help if you could provide a sample code and info if you are reproducing this issue on iOS or Android.

In the meantime, you could review the demo application in the [plugins repository](https://github.com/NativeScript/nativescript-imagepicker/tree/master/demo) and verify, whether you will have the same issue.
