### ISSUE TITLE
Single tap does not work on Android

### ISSUE THREAD

**Issue by poisytu** [NativeScript/nativescript-imagepicker#12]
Hi, I noticed that multi selection is working fine, but if you select just one it doesn`t work okay. If you debug the selection is empty.

**Comment by NickIliev** [comment]
Hello,
We have made a working example in which both single and multiple selections are working fine. 
Can you please provide some additional code so we can assist you further?

**Comment by poisytu** [comment]
HI, I am using the example that you have created, but when I try to select a single picture, it doesn`t show the thumbnail in a listview (this happens only on android, on IOS it is fine). And when I try to debug and check the selection it is empty.

**Comment by PanayotCankov** [comment]
@poisytu We use Intent in android and maybe we don't handle all possible result variants. Could you share details about the device and android API version this happened on?

**Comment by PanayotCankov** [comment]
We are publishing new version where the resolution of the selection was changed. Please give it a try again.
