### ISSUE TITLE
Selection.getImage() crash on android when using maxWidth

### ISSUE THREAD

**Issue by AlanChauchet** [NativeScript/nativescript-imagepicker#126]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
### Which platform(s) does your issue occur on?
- Android
- Android 7.0
- Samsung Galaxy S7 Edge

### Please, provide the following version numbers that yourissue occurs with:

- CLI: 3.2.1
- Cross-platform modules: 3.2.0
- Runtime(s): 3.1.1
- Plugin(s): tested with 3.0.6 / 4.0.0

### Please, tell us how to recreate the issue in as much detail as possible. 
When opening the image picker and selecting a single picture (with mode = 'simple'), if I call the function getImage with an option set to for example { maxWidth: 500 } /*or any other value*/ then the imagePicker show a black screen and never goes back to the app. If I dont set any option while using getImage, everything works fine

### Is there any code involved? 
 ```
permissions.requestPermission([
    'android.permission.READ_EXTERNAL_STORAGE',
    'android.permission.WRITE_EXTERNAL_STORAGE',
    'android.permission.CAMERA',
    'android.permission.RECORD_AUDIO',
])
    .then(() => {
        const context = imagepickerModule.create({
            mode: multiple ? 'multiple' : 'single',
            doneText: this.translateService.translateInstant('COMMONS.CONFIRM'),
            cancelText: this.translateService.translateInstant('COMMONS.CANCEL'),
            newestFirst: true
        });
        return context.authorize()
            .then(() => context.present())
            .then((selections) => {
                const selection = selections[0] || null;
                if (selection) {
                    selection.getImage({ maxWidth: 500 })
                        .then(imgSrc => ... )
                }
            })
    });
```

**Comment by radeva** [comment]
Hi @AlanChauchet ,

Thanks for reporting the issue. It looks like the [check for width and height](https://github.com/NativeScript/nativescript-imagepicker/blob/master/src/imagepicker.android.ts#L207) in the Android implementation needs to be improved when height is not specified. 

We should fix this check in the next version of the plugin but a pull request will be also highly appreciated.

Best regards,
Veselina

**Comment by AlanChauchet** [comment]
Hi @radeva ,

I just made a PR with some check for the width and height on Android that should fix it.
Hope that helps,

Alan

**Comment by radeva** [comment]
Thank you @AlanChauchet for the quick reaction! 
Your PR is merged and the fix will be available in the next version.

Best regards,
Veselina

**Comment by jlooper** [comment]
Congratulations! This contribution earned a special badge for quality!

![contrib](https://user-images.githubusercontent.com/1450004/32003599-93fe42fc-b96d-11e7-8c96-7ad18eed7ce3.png)
