### ISSUE TITLE
ImagePicker crashing when selecting photos downloaded with 'data:image'

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-imagepicker#13]
Using browser to download and save images to /Downloads in local storage sometimes images are refered not with **https://path-to-image** but with **data:image/jpeg;base34/path-to-image** .. in this case the imagepicker is not able to select the image later. 
Issue discovered with Android emulator under {N} 1.7.0.

**Comment by NickIliev** [comment]
Different API Level emulators responds differently!
- API 23 with Nexus 6 is getting the image via **data:url**
- The same image is on API 19 with Nexus 4 is downloaded via **http**

**Comment by PanayotCankov** [comment]
We will try to discourage fileUri usage.
