### ISSUE TITLE
Error More than one library with package name 'com.telerik.android.common'

### ISSUE THREAD

**Issue by EduhCosta** [NativeScript/nativescript-imagepicker#137]
Hi everyone, I just installed the plugin in my project and returned this error in the android build, can someone help me?

### --log trace

_13:56:43.510 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
13:56:43.512 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
Unable to apply changes on device: 192.168.56.101:5555. Error is: Command ./gradlew failed with exit code 1.
Project dir from hooksArgs is: /Users/eduardocosta/Documents/01-Apps/.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/eduardocosta/Documents/01-Apps/./hooks' ]
AfterHookName for command watch is after-watch
Executing after-watch hook from /Users/eduardocosta/Documents/01-Apps/./hooks/after-watch/nativescript-dev-typescript.js
Executing after-watch hook at location /Users/eduardocosta/Documents/01-Apps/./hooks/after-watch/nativescript-dev-typescript.js in-process
Validating after-watch arguments.
Hook completed
Project dir from hooksArgs is: /Users/eduardocosta/Documents/01-Apps/..
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/eduardocosta/Documents/01-Apps/./hooks' ]
AfterHookName for command liveSync is after-liveSync_

### tns run android

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5UniversalDebugResources'.
> Error: more than one library with package name 'com.telerik.android.common'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.965 secs
Unable to apply changes on device: 192.168.56.101:5555. Error is: Command ./gradlew failed with exit code 1.
Executing after-watch hook from /Users/eduardocosta/Documents/01-Apps/BioPagueClient/hooks/after-watch/nativescript-dev-typescript.js

=============================

### Package.json

>  {
>    "description": "NativeScript Application",
>    "license": "SEE LICENSE IN <your-license-filename>",
>    "readme": "NativeScript Application",
>    "repository": "<fill-your-repository-here>",
>    "nativescript": {
>      "id": "org.nativescript.BioPagueClient",
>      "tns-ios": {
>        "version": "3.2.0"
>      },
>      "tns-android": {
>        "version": "3.2.0"
>     }
>    },
>    "scripts": {
>      "lint": "tslint \"app/**/*.ts\""
>    },
>    "dependencies": {
>      "@angular/animations": "4.2.5",
>      "@angular/common": "4.2.5",
>      "@angular/compiler": "4.2.5",
>     "@angular/core": "4.2.5",
>     "@angular/forms": "4.2.5",
>      "@angular/http": "4.2.5",
>      "@angular/platform-browser": "4.2.5",
>      "@angular/router": "4.2.5",
>      "nativescript-angular": "4.2.0",
>      "nativescript-barcodescanner": "^2.7.0",
>      "nativescript-carousel": "^3.1.1",
>      "nativescript-gradient": "^2.0.1",
>      "nativescript-imagepicker": "^4.0.1",
>      "nativescript-intl": "^3.0.0",
>      "nativescript-ngx-slides": "^0.4.2",
>      "nativescript-telerik-ui": "3.0.4",
>      "nativescript-theme-core": "1.0.4",
>     "nativescript-zxing": "^1.5.2",
>     "ng2-search-filter": "^0.3.1",
>      "reflect-metadata": "0.1.10",
>      "rxjs": "5.4.3",
>      "tns-core-modules": "3.1.1",
>      "zone.js": "0.8.16"
>    },
>    "devDependencies": {
>      "babel-traverse": "6.26.0",
>      "babel-types": "6.26.0",
>      "babylon": "6.18.0",
>      "codelyzer": "3.1.2",
>      "lazy": "1.0.11",
>      "nativescript-dev-sass": "1.3.0",
>      "nativescript-dev-typescript": "0.5.0",
>      "node-sass": "4.5.3",
>      "tslint": "5.6.0",
>      "typescript": "2.4.2"
>    }
>  }

**Comment by tsonevn** [comment]
Hi @EduhCosta ,

Since the announcement that NativeScript UI is free, the nativescript-telerik-ui and nativescript-telerik-ui-pro plugins have been deprecated in favor of nativescript-pro-ui which has the same components as nativescript-telerik-ui-pro. Regarding that I would suggest to migrate to the new plugin called `nativescript-pro-ui` as it is described [here ](http://docs.telerik.com/devtools/nativescript-ui/migration) in the documentation and to verify, whether the issue still persists.

**Comment by EduhCosta** [comment]
Hi @tsonevn ,

I changed my package.json, deleted the last android platform and rebuilded the project, but i still with the same error =/

**Comment by EduhCosta** [comment]
Correcting, the error was the same guy, I was just editing `package.json`, as indicated in the link, but in fact I should use `npm` for this.

Good mistake I did, and that's OK. Thank you @tsonevn

**Comment by Arshadkukun** [comment]
I to had the same issue......  and able to solve .
Thank you @tsonevn
