### ISSUE TITLE
Images are not displaying in iOS device after selection.!!

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/nativescript-imagepicker#138]
Hi,
I am using this plugin to select the pictures from the gallery and display it in the view.the problem is the images are not displaying in iOS but working fine in android and even simulator.
What might be the problem?

**Comment by NickIliev** [comment]
@sagar1911 please consider providing the code base you are using to display the selected images on iOS.
Without the actual code used on your side it is hard to investigate and uncover the reasons for your issue.

Meanwhile, you can use[ this sample applicaiton](https://github.com/NativeScript/sample-ImageUpload) that selects and visualizes images via the plugin for both iOS and Android.

**Comment by sagar1911** [comment]
Hi @NickIliev,
Thanks for the response. Here is my code
`var context = imagePicker.create({
        mode: "multiple"
    });
    viewModel.displayImages = new observableArray();

    context
        .authorize()
        .then(function () {
            return context.present();
        })
        .then(function (selection) {
            // assigning the selected images to a variable so that they can be accessible
            selectedImages = selection;
            displayImagesGrid.removeChildren();
            showImages(selectedImages);
        }).catch(function (e) {
            // process error
            console.log("error in image picker is "+e);
        });`


`showImages = function(processingImages) {
    viewModel.blueBoxVisibility = "visible";
    var currentColumn = 0;
    var currentRow = 0;
    var fileUris = [];
    processingImages.forEach(function(ele, index) {
        fileUris[index] = ele.fileUri;
    })
    viewModel.demoImage = fileUris[0];
    for (let i = 0; i < fileUris.length; i++) {
        let imageStack = new stackLayoutModule();
        let imageSource = new imageModule();
        imageSource.src = fileUris[i];
        imageSource.stretch = "aspectFill";

        imageStack.addChild(imageSource);
        imageStack.id = "imageStack";
        imageStack.class = "grid-image";

        if (currentRow == 0) {
            column = new gridLayoutModule.ItemSpec(viewModel.itemWidth, "pixel");
            displayImagesGrid.addColumn(column);
        }
        if (currentColumn == 0) {
            row = new gridLayoutModule.ItemSpec(viewModel.itemWidth, "pixel");
            displayImagesGrid.addRow(row);
        }
        imageStack.on("tap", function() {
            viewModel.demoImage = fileUris[i];
            viewModel.blueBoxVisibility = "visible";
        })
        displayImagesGrid.addChild(imageStack);
        new gridLayoutModule.GridLayout.setRow(imageStack, 0);
        new gridLayoutModule.GridLayout.setColumn(imageStack, currentColumn);
        currentColumn += 1;
    }
}`

**Comment by NickIliev** [comment]
@sagar1911 check what `ele.fileUri;` is returning in your code snippet.
The thing is that on iOS images from the gallery are usually PHAssets and they cannot be directly accessed (no usable path) - so the solution would be to save the mage in your own path and use this path to visualize it in your UI. For example take a look how I have handles this [here](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L109-L115)

**Comment by sagar1911** [comment]
Yes. thanks @NickIliev ,
I have just now implemented it based on your code. Now its working fine
Thanks a lot 😄
