### ISSUE TITLE
OutOfMemoryError in android while selecting multiple images.

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/nativescript-imagepicker#139]
Hi,
I am using the image picker to select multiple images from the gallery. 
If I select more than 8 images of size 4 MB each I am getting this error on android.
In iOS, for the same case, it is not showing any error but images are not rendering in the view.

If I select low size images it is working fine in both iOS and android.

![screenshot_2017-12-11-18-22-10-898_com divami aqua](https://user-images.githubusercontent.com/30491548/34091127-ae28a32c-e3e1-11e7-9b81-80792c02d921.png)

Any idea how can I solve this ??

**Comment by tsonevn** [comment]
Hi @sagar1911,
I tested your case while using the [demo application](https://github.com/NativeScript/nativescript-imagepicker/tree/master/demo) provided in the plugin's repository, however, I was unable to recreate a similar issue.
Regarding that, it would help if you could provide some more info about your environment(modules, CLI, node, npm versions) and sample project, which could be used for debugging.

**Comment by sagar1911** [comment]
Thanks for the reply @tsonevn ,
Here is my package.json
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "com.divami.aqua",
		"tns-ios": {
			"version": "3.2.0"
		}
	},
	"dependencies": {
		"install": "^0.10.2",
		"nativescript-barcodescanner": "^2.7.1",
		"nativescript-carousel": "^3.1.1",
		"nativescript-imagepicker": "^4.0.1",
		"nativescript-na-camera": "^1.2.0",
		"nativescript-theme-core": "~1.0.2",
		"tns-core-modules": "~3.2.0"
	}
}


This is image picker code

context
        .authorize()
        .then(function () {
            return context.present();
        })
        .then(function (selection) {
            // assigning the selected images to a variable so that they can be accessible
            selectedImages = selection;
            displayImagesGrid.removeChildren();
            getPaths(selectedImages);
        }).catch(function (e) {
            // process error
            console.log("error in image picker is " + e);
        });

**Comment by tsonevn** [comment]
Hi @sagar1911,
I tested further your case while reusing some part of the provided code, however, was unable to recreate similar crash. There is missing info about the getPaths method and its functionality. Also, it is not clear enough, what do you expect as a final result. 
For your convenience, I am attaching sample project, please review it and make the needed changes, which will allow us to recreate the issue. 
[Archive.zip](https://github.com/NativeScript/nativescript-imagepicker/files/1568457/Archive.zip)

**Comment by sagar1911** [comment]
Sorry @tsonevn , Here is the complete code regarding the error

`var customImagePaths = [];
getPaths = function (processingImages) {
    viewModel.blueBoxVisibility = "visible";
    var fileUris = [];
    if (platform.device.os == "iOS") {
        var counter = 0;
        processingImages.forEach(function (selected_item, index) {
            selected_item.getImage().then(function (imagesource) {
                var localPath = null;
                // selected_item.ios for iOS is PHAsset and not path - so we are creating own path
                let folder = fs.knownFolders.documents();
                let path = fs.path.join(folder.path, "Test" + counter + ".png");
                let saved = imagesource.saveToFile(path, "png");

                localPath = path;

                if (localPath) {
                    customImagePaths[counter] = localPath;
                }
                counter++;
                if (processingImages.length == counter) {
                    showImages(customImagePaths);
                }
            })
        });
    } else {
        processingImages.forEach(function (ele, index) {
            customImagePaths[index] = ele.fileUri;
        })
        showImages(customImagePaths);
    }
}`

// show images in carousel view
`showImages = function (selectedImages) {
    // clearing view before selecting every time
    viewModel.displayImages = new observableArray();
    var fileUris = [];

    // for each image adding itemWidth and filePath
    for (let i = 0; i < selectedImages.length; i++) {
        fileUris[i] = {};
        fileUris[i].itemWidth = deviceWidth / 5;
        fileUris[i].filePath = selectedImages[i];
    }

    // setting number of images in each carousel view
    var numOfImages = 5;
    for (var i = 0; i < fileUris.length; i = i + numOfImages) {
        var eachCarousel = {};
        // adding each carousel view
        eachCarousel.files = fileUris.slice(i, i + numOfImages);
        viewModel.displayImages.push(eachCarousel);
    }

    // displaying the first image after deletion
    viewModel.demoImage = fileUris[0].filePath;
    viewModel.blueBoxVisibility = "visible";

    page.bindingContext = viewModel;
}`

This is xaml code

`<GridLayout visibility="visible" height="{{ carouselHeight }}" margin="0,0,0,0">
                                    <ns:Carousel items="{{ displayImages }}" height="100%" indicatorColorUnselected="#EAECED" indicatorColor="#000000" pageChanged="myChangeEvent" pageScrolling="myScrollingEvent">
                                        <ns:Carousel.itemTemplate>
                                            <ns:CarouselItem verticalAlignment="center">
                                                <GridLayout rows="80">
                                                    <Repeater items="{{ files }}">
                                                        <Repeater.itemsLayout>
                                                            <WrapLayout />
                                                        </Repeater.itemsLayout>
                                                        <Repeater.itemTemplate>
                                                            <Image src="{{ filePath }}" width="{{ itemWidth }}" tap="onImage" stretch="aspectFill" />
                                                        </Repeater.itemTemplate>
                                                    </Repeater>
                                                </GridLayout>
                                            </ns:CarouselItem>
                                        </ns:Carousel.itemTemplate>
                                    </ns:Carousel>
                                </GridLayout>`

**Comment by sagar1911** [comment]
Sorry, My code looks cumbersome to read.I'll do one thing let me try the code you have provided first then I'll come back to you.
Thanks a lot

**Comment by sagar1911** [comment]
Hi @tsonevn ,
I found the reason for the error. The problem is I was calling the function which is rendering the images twice. It was my mistake nothing to do with the plugin. thanks
