### ISSUE TITLE
App crashes as Selected fileUri becomes undefined in the device running ios 9.3

### ISSUE THREAD

**Issue by sowrabhbs** [NativeScript/nativescript-imagepicker#14]
But Shows valid  fielUri in the simulator.

**Comment by nicheledany** [comment]
Also in iOS 9.2

**Comment by Daxito** [comment]
You can check #25 , it has a workaround to get the image source instead.

**Comment by PanayotCankov** [comment]
@Daxito it is not a workaround but the right way to do it. Both Android and iOS can't promise to give reliable file url. iOS 9.2 now returns path in the simulator on my machine that can't be used for background upload.

And for **iOS 10** you may need to add:
```
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app want to send your photos to your BF...</string>
```
In the app/App_Resources/iOS/Info.plist
