### ISSUE TITLE
The plugin removes NSPhotoLibraryUsageDescription string from plist

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-imagepicker#145]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
When plugin is installed it removes NSPhotoLibraryUsageDescription string from plist added by nativescript-camera

### Which platform(s) does your issue occur on?
- iOS

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1
- Plugin(s): 
nativescript-pro-ui: 3.3.0
nativescript-camera: 3.2.1
nativescript-imagepicker: 4.0.1

### Please, tell us how to recreate the issue in as much detail as possible. 

1. tns create imagepickertest --template tsc
2. tns plugin add nativescript-camera@3.2.1
3. tns build ios
4.  now go to platforms/ios/imagepickertest/imagepickertest-Info.plist and find NSPhotoLibraryUsageDescription key. Under that key you should have a string with description saying "Requires access to photo library."
5. tns plugin add nativescript-imagepicker@4.0.1
6. tns build ios
7. do the same as in the step 4, the string should be empty.

Expected result the description should not be removed.

### Is there any code involved? 
Please follow the steps above.

**Comment by DimitarTodorov** [comment]
Hi @terreb, 

Each NativeScript plugin can have its own info.plist configuration in order to write the key-string values for permission which it will require. If you want to control the value for the desired key-string pair you should write it in the info.plist file in the App_Resources/iOS folder of your application. This value will be used with priority and will not be overwritten by a plugin.

Regards.

**Comment by terreb** [comment]
Hi @DimitarTodorov, thank you for your reply. I do agree each plugin may change info.plist configuration, but can you at least add a generic description there, rather than leaving its empty? Something like "the app requires access to your photo library" would do.

Regards.

**Comment by DimitarTodorov** [comment]
Hi @terreb,
I added a message in the info.plist file for the required photo library access.

Regards.

**Comment by terreb** [comment]
@DimitarTodorov, thank you! 

Regards.
