### ISSUE TITLE
How to run the demo application?

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-imagepicker#147]
I get this error message when I go to `demo-angular` folder and try to run the application.
<img width="271" alt="ekran resmi 2018-01-21 16 36 14" src="https://user-images.githubusercontent.com/11949947/35194745-4c1f0574-fec9-11e7-9c1d-4b9beaa0b7f3.png">

**Comment by NickIliev** [comment]
@erkanarslan see [the README file](https://github.com/NativeScript/nativescript-imagepicker/tree/master/demo) from the demo
```
This NativeScript project demonstrates how the plugin works.
If you want to test it out on an emulator or a device you can follow the instructions below:

* `git clone https://github.com/NativeScript/nativescript-imagepicker.git`
* `cd nativescript-imagepicker/demo` or `cd nativescript-imagepicker/demo-angular`
* `npm run build.plugin && npm install`
* `tns run android` or `tns run ios` depending on the platform you want to test
```
