### ISSUE TITLE
App crashes in iOS.

### ISSUE THREAD

**Issue by halaharr** [NativeScript/nativescript-imagepicker#149]
Hi,
     App crashes if I select about 15 to 20 images in iOS. Wondering if any one is having the same issue?

Thanks

**Comment by tsonevn** [comment]
Hi @halaharr,
I tested your scenario with the [demo](https://github.com/NativeScript/nativescript-imagepicker/tree/master/demo) application provided in the repository, however, was unable to recreate the similar issue on an iOS device and latest NativeScript 3,4,1.

Could you provide a sample application, which will allow us to recreate this behavior?

**Comment by halaharr** [comment]
Hi,
    Thanks for the response. I think it was crashing because the app was trying to read all the images without scaling to maxWidth and maxHeight. Once I started scaling the problem went away. It must be because of reading so many images was causing memory issue.

Thanks

**Comment by tsonevn** [comment]
Hi @halaharr,
Thank you for the response
Regarding your last comment, I considered that the issue is resolved on your side.
