### ISSUE TITLE
Full Image Loading

### ISSUE THREAD

**Issue by KallynGowdy** [NativeScript/nativescript-imagepicker#15]
It would be beneficial for consumers of this API if we could retrieve full images using the image picker in the form of an `ImageSource`. This way we are not limited to 100x100 pixel thumbs. 

Additionally, it would be nice if the API exposed a way to use promises for retrieving either thumbs or full images. As it stands right now, the iOS API appears synchronous, but is actually asynchronous, while the Android API is fully synchronous.

I can implement all of this and submit a pull.

**Comment by PanayotCankov** [comment]
@KallynGowdy
Go for it!
The image picker definitely needs this!

I am aware that fixed thumb size is a problem. I just hoped that we will have time to implement an interface in the core framework, that the Image view will provide its actual size and scale settings to and request asynchronously ImageSource from. Then frameworks such as the nativescript-imagepicker would be able to implement that interface and allow the Image view's src to bind directly to the image-picker results without requiring additional JS code to handle the promises. It would also allow services such as the Everlive to provide abstraction for images that will handle re-sizing on demand in the cloud. Then given we already have support for some pseudo-selectors and CSS animations, our image view could switch states using CSS and CSS animations to display "loading" state and when ready "intro" animation or "error" state. We are not there yet, however the API you want to implement is a step in the right direction!

**Comment by KallynGowdy** [comment]
Ok, here is my official proposal for the changes that will be made:

Two methods will be added to the common SelectedAsset API between iOS and Android:

A). An asynchronous method that, given an object that represents image size options, returns a `ImageSource` object that represents the scaled image data. Passing `null` or `undefined` for the options will cause the image to be returned manipulated.

```typescript

interface ImageOptions {
    /**
     * The maximum size that the image is able to be in either direction.
     */
    maxSize: number;
}

/**
 * Retrieves an ImageSource object that represents this selected image.
 * Scaled to the given size.
 */
getImage(options?: ImageOptions): Promise<ImageSource>;
```

B). An asynchronous method that returns the raw image data as an `ArrayBuffer`.

```typescript
/**
 * Retrieves an ArrayBuffer that represents the raw byte data from this selected image.
 */
getImageData(): Promise<ArrayBuffer>;
```

Additionally, depreciation notices will be added to `thumb` and `data()`, notifying consumers to use `getImage()` and `getImageData()`.
This way, the behavior of `thumb` and `data()` will be preserved, while providing an clear API for future use.

I will probably get around to creating an initial PR for this proposal on Thursday, with completion targeted for Saturday.

**Comment by PanayotCankov** [comment]
`maxWidth`/`maxHeight` pair is better than general maxSize.

In future we may add `stretch` and `position` properties similar to the CSS background properties. Stretch would control if the image is larger it would be clipped or scaled down, while position will control which part of the image will be clipped if it have to be clipped at all.

Ultimately displaying the full original image in small area using CSS background-* properties, should apear the same as if we pass these to the `getImage` to retrieve the thumb and then display the thumb using the same properties. 

@slavchev @jasssonpet:
Can we cheaply wrap native byte[] in ArrayBuffers? I think data() currently returns NSData and perhaps byte[] for android.

**Comment by jasssonpet** [comment]
@PanayotCankov It is possible at the moment, though a bit non trivial. You can wrap the `byte[]` in an `NSData` (without copying the byte array) and pass it to the `interop.bufferFromData(data)` function which will return an `ArrayBuffer` (without copying the `NSData` contents).

```javascript
var arrayBuffer = interop.bufferFromData(NSData.dataWithBytesNoCopyLength(byteArray, byteArrayLength));
```

**Comment by slavchev** [comment]
@PanayotCankov The Android story is a bit rough. Currently we support no-copy marshalling of `java.nio.ByteBuffer` only.

**Comment by PanayotCankov** [comment]
@jasssonpet https://github.com/NativeScript/ios-runtime/blob/master/src/ts/Interop.d.ts#L77 is perfect. The underlying API returns NSData anyway. :)

**Comment by ckhordiasma** [comment]
Hello, I've been looking at trying to use this image selector for single image selections on Android, and I was having some troubles with getting an `ImageSource` object out of this plugin.

Using the following imports,

```
var imageSource = require('image-source');
var imagePickerModule = require("nativescript-imagepicker");
```

I have the following code which does not work:

```
     var context = imagePickerModule.create({
         mode: "single"
      });
      context.authorize().then(function(){
          return context.present();
       })
       .then(function(pickedPictures){
           var size = {
               maxWidth: 100,
               maxHeight: 100
           };
         return pickedPictures[0].getImage(size)
           .then(function(pickedPicture){
               // Take care of tying the ImageSource object to the page here
         });              
      }); 
```

I'm not very familiar with using TypeScript, but looking at the code for the viewmodel.android.ts file, does there need to be some sort of additional method to allow users to access the `getImage()` function? Similar to the `get` functions for the `uri`, `thumb`, and `fileUri` properties that look like 

```
    get thumb(): imagesource.ImageSource {
        if (!this._thumbRequested) {
            this.decodeThumbUri();
        }
        return this._thumb;
    }

    get uri(): string {
        return this._uri.toString();
    }

    get fileUri(): string {
        if (!this._fileUri) {
            this._fileUri = this._calculateFileUri();
        }
        return this._fileUri;
    }
```
If not, is there something I am doing wrong with my implementation of this module?

**Comment by KallynGowdy** [comment]
@ckhordiasma Can you provide more detail than `"which does not work"`? Is `getImage()` throwing an exception? Is it returning `null`? The more specific details on what is currently happening that you can provide, the better we can resolve this issue. Also, I'm going to close this issue as it is supposed to be complete. Can you open another issue with your problem and answer my questions there?
