### ISSUE TITLE
Image grid collapsing to image width after suspend / resume

### ISSUE THREAD

**Issue by KilianSSL** [NativeScript/nativescript-imagepicker#155]
### Which platform(s) does your issue occur on?
- iOS 10/11.2.2/11.3
- iPhone 6S, iPhone 7, iPhone X

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.5.0-2017-12-12-10240
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.0
- Plugin(s): as demo-angular

### Please, tell us how to recreate the issue in as much detail as possible. 
Using nativescript-imagepicker/demo-angular

First thought it occurs randomly, but i have one way to consistently reproduce it
1. Go to "Pick One"
2. Select a gallery
=> Image Grid has squared containers
3. Suspend the app (Home Button)
4. Resume to the app
=> Image Grid containers have collapsed to image width

Please find the ZIP attached with two screenshots..
[nativescript-imagepicker-grid-bug.zip](https://github.com/NativeScript/nativescript-imagepicker/files/1724481/nativescript-imagepicker-grid-bug.zip)

**Comment by NickIliev** [comment]
@KilianSSL are you using some of the demo applications or your own code base?

**Comment by KilianSSL** [comment]
I'm using demo-angular. I have edited the original issue above.

**Comment by NickIliev** [comment]
Reproducible with the demo applications and the steps described above

**Comment by tbozhikov** [comment]
This is going to be fixed with #172

**Comment by tbozhikov** [comment]
@KilianSSL I am closing the issue as it is covered in [6.0.0](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.0). Feel free to write (reopen) if you still experience problems with that.
