### ISSUE TITLE
The selected image in the album is not obvious

### ISSUE THREAD

**Issue by LSmint** [NativeScript/nativescript-imagepicker#167]
The selected images opacity become lower but it still very hard to let user figure out that image is selected. Can add a tick or border to make it more obvious?

**Comment by radeva** [comment]
Hi @LSmint ,

Is this something you experience on both iOS and Android or it's specific for any of the platforms? 
This sounds an feature easy for contribution so feel free to do a pull request and improve the experience.

**Comment by tbozhikov** [comment]
Closing this since the new [6.0.0](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.0) version is out and it solves the issue.
