### ISSUE TITLE
Invalid URI

### ISSUE THREAD

**Issue by Nixon1979** [NativeScript/nativescript-imagepicker#17]
I am getting the below issue when I try to access fileUri

JS:  - content://media/external/images/media/21121
JS: Error: java.lang.IllegalArgumentException: Invalid URI: content://media/external/images/media/21121

 context
                                    .authorize()
                                    .then(function() {
                                        return context.present();
                                    })
                                    .then(function(selection) {
                                        console.log("Selection done:");
                                        selection.forEach(function(selected) {
                                            console.log(" - " + selected.fileUri);
                                           registerData.mpPhoto = selected.fileUri;
                                        });
                                    }).catch(function (e) {
                                        console.log(e);
                                    });

version of imagepicker -     "nativescript-imagepicker": "0.0.4",

**Comment by NickIliev** [comment]
related to issue [https://github.com/NativeScript/nativescript-imagepicker/issues/13](https://github.com/NativeScript/nativescript-imagepicker/issues/13)

**Comment by Daxito** [comment]
Check #25 as a workaround by getting the image source instead.

**Comment by terreb** [comment]
Any update on this? I'm using version 0.0.6 of the plugin and still get this issue on Android (Genymotion emulator Samsung Galaxy S6, Android 5.1.0). Step to reproduce: clone and run https://github.com/NativeScript/sample-ImageUpload in debug mode.

**Comment by PanayotCankov** [comment]
fileUri will always be unreliable in both platforms, in some cases there would be insufficient permissions, in others, the images may be still in the cloud and have yet to be downloaded. Please use `getImage` and `getImageData`. We are currently working toward making fileUri return simple null instead of crashing.
