### ISSUE TITLE
Use albums.xml on android too

### ISSUE THREAD

**Issue by devlfm** [NativeScript/nativescript-imagepicker#170]
Hi,

I'm not sure if I'm doing something wrong, but on android, when I open the Intent, the view that show, is the system gallery. 

I need a custom view that lists the albums and photos thumbnails. Is the albums.xml only used for ios?

**Comment by NickIliev** [comment]
@devlfm the `albums` property is available only on iOS.

**Comment by tbozhikov** [comment]
Hi @devlfm. The purpose of this plugin (and most of the {N} core ones) is to look as native as possible for both **Android** and **iOS**. That is why it behaves and looks as you experience. If you want custom looks, maybe the best option is to design it/implement it from the ground-up or wrap an existing library in a separate {N} plugin. If we implement advanced styling options in this one, this will bring complexity, bugs, not needed payload for users that use just the basic picking functionality. 

I am closing this, feel free to reopen it if you have further questions related to that matter.

P.S.: FYI, to make the iOS experience even more native, with the [latest version](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.0) of the imagepicker plugin the albums.xml file is no more present, as we've wrapped the [QBImagePicker](https://github.com/questbeat/QBImagePicker) cocoa pod.
