### ISSUE TITLE
selected.getImage is not a function

### ISSUE THREAD

**Issue by pierremacedo** [NativeScript/nativescript-imagepicker#181]
I'm making an app where some data are stored in a SQL database. But in order to store images and videos I need to get the file uri first. I tried everything I could but nothing worked.

This is how my JS file looks like:

```
var imagepicker = require("nativescript-imagepicker");
var permissions = require( "nativescript-permissions" );
var ImageSourceModule = require("image-source");

function openImage() { 
   var context = imagepicker.create({ mode: "single" }); // use "multiple" for multiple selection
        context
    .authorize()
    .then(function() {
        return context.present();
    })
    .then(function(selection) {
        selection.forEach(function(selected) {
            selected.getImage().then((source) => {
                    console.log(selected.fileUri); 
                });     
        });  
    }).catch(function (e) {
        alert(e);// process error
    });
}


exports.openImage = openImage;
```
I can select images without a problem but then I get this error  "selected.getImage is not a function".

**Comment by kvindasAB** [comment]
Pierre im facing a similar issue, well, not exactly, but on the latest version of the plugin v6, the selection is really an ImageAsset from nativescript and it is not exactly working as the code you indicate.
That should work for version 5 and before, but Im also still in the process to understand how it is supposed to work on the latest version, because I see no fileUri or similar properties.

**Comment by lini** [comment]
I tested this using the latest (6.0.1) version of the image picker plugin. For Android, getting the image path is very easy. Assuming `selection` is the array of image assets returned from the image picker:

```javascript
selection.forEach(function(selected) {
     console.log(selected.android.toString()); 
});
```

For iOS, it is a bit more tricky as the native PHAsset object does not have a property containing the path:

```javascript
selection.forEach(function(selected) {
    const ios = selected.ios;
    if (ios && ios.mediaType === PHAssetMediaType.Image) {
        const opt = PHImageRequestOptions.new();
        opt.version = PHImageRequestOptionsVersion.Current;
        PHImageManager.defaultManager().requestImageDataForAssetOptionsResultHandler(
            ios, opt, (imageData: NSData, dataUTI: string, orientation: UIImageOrientation, info: NSDictionary<any, any>) => {
                console.log(info.objectForKey("PHImageFileURLKey").toString());
            });
        }
    }
});
```

**Comment by bachras** [comment]
@lini thank you for sharing your solution. Can you provide whole component code? As it says it cannot find NSData, UIImageOrientation, NSDictionary . I try to declare them but it didn't help. I haven't worked with native iOS code before. Thank you in advance.

**Comment by lini** [comment]
You need to add the `tns-platform-declarations` dependency to your app. It contains the definitions for all native objects like NSData and UIImageOrientation.

**Comment by bachras** [comment]
thanks @lini

**Comment by snq** [comment]
@lini I still have problem with this. This is the how my `selected` looks like:

JS: {
JS:   "_observers": {},
JS:   "_options": {
JS:     "keepAspectRatio": true
JS:   },
JS:   "_android": ""
JS: }

**Comment by sivamamidi-REISys** [comment]
+1

**Comment by sivamamidi-REISys** [comment]
Please provide good documentation for last two versions.

**Comment by ppulwey** [comment]
Sorry, to start the question here again, but how can I get the path to a **Video**?
I've tried to figure it out by myself, but I stuck. What I have so far:
`imagepicker.create({
          maximumNumberOfSelection: 1,
          minimumNumberOfSelection: 1,
          mediaType: imagepicker.ImagePickerMediaType.Video,
          mode: 'single',
          prompt: 'Bitte Video auswählen'
        }).present()
          .then(
            (videoAsset: any) => {
              //console.log(videoAsset[0].ios);
              //resolve(videoAsset[0].ios);

              const selected = videoAsset[0];

              const ios = selected.ios;
              
              if (ios) {
                const opt = PHVideoRequestOptions.new();
                opt.version = PHVideoRequestOptionsVersion.Current;

                //console.dir(PHImageManager.defaultManager());
                PHImageManager.defaultManager().requestAVAssetForVideoOptionsResultHandler(
                  ios, opt, (asset: AVAsset, audioMix: AVAudioMix, info: NSDictionary<any, any>) => {
                    /* console.log('asset', asset);
                    console.log('audioMix', audioMix);
                    console.log('info', info); */
                    console.log(info.objectForKey("PHImageFileURLKey").toString());
                  });
              }
            },
            (rej) => {
              console.log(rej);
            });`

But this is not working. Any ideas / solutions?

**Comment by ehibes** [comment]
@ppulwey this works for me :
```
const selected = selection[0];
const ios = selected.ios;

if (ios) {
  const opt = PHVideoRequestOptions.new();
  opt.version = PHVideoRequestOptionsVersion.Current;
  PHImageManager.defaultManager().requestAVAssetForVideoOptionsResultHandler(
    ios, opt, (asset: AVAsset, audioMix: AVAudioMix, info: NSDictionary<any, any>) => {
      let regex = /(file[^>]*)/g
      let file = asset.toString().match(regex)[0];
      console.log(file);
    });
}
```

**Comment by falodunos** [comment]
@pierremacedo find my complete solution here ... 

`https://github.com/NativeScript/nativescript-imagepicker/issues/197#issuecomment-431783669`

**Comment by ibnYusrat** [comment]
How do we copy the image to app's directory to be able to actually make some use of that path?

**Comment by keerl** [comment]
This no longer works on iOS 13. `PHImageFileURLKey` has been deprecated. https://stackoverflow.com/questions/57202965/phimageresultisdegradedkey-phimagefileurlkey-is-not-found

**Comment by uzarsalan** [comment]
Working solution

```typescript
const ios: PHAsset = selected.ios;
            if (ios && ios.mediaType === PHAssetMediaType.Image) {
              filePath = await new Promise((resolve, reject) => {
                ios.requestContentEditingInputWithOptionsCompletionHandler(
                  null,
                  (input, info) => {
                    resolve(
                      input.fullSizeImageURL.toString().replace("file://", "")
                    );
                  }
                );
              });
            }
```

**Comment by dmoptimal** [comment]
@uzarsalan I'm using your example and it works occasionally for me, but quite often (especially with older photos) I get this error when selecting an image:

`TypeError: null is not an object (evaluating 'input.fullSizeImageURL')
`

I logged the info & input params inside the function and I see this:

info:
```
{
    PHContentEditingInputErrorKey = "Error Domain=PHPhotosErrorDomain Code=3164 \"(null)\"";
    PHContentEditingInputResultIsInCloudKey = 1;
    PHImageResultRequestIDKey = 21;
}
```

input:
`null`

Does anyone know what this issue is? I'm guessing its something to do with iCloud maybe? as in, photos backing up to iCloud, then no longer being "on device". I'm new to this so not exactly sure.
