### ISSUE TITLE
stuck at context.authorize() after update to 6.0.1

### ISSUE THREAD

**Issue by giorgi-abashidze** [NativeScript/nativescript-imagepicker#182]
I updated plugin and it stucks at context.authorize(), it logging : authorizing... and thats it.
it opens gallery but when i tap on image, gallery window closing and nothing happens

**Comment by ogmedia** [comment]
Noticed the same thing.

In the debugger I noticed there is a method named getImageAsync(). Trying that now.

**Comment by ogmedia** [comment]
Nevermind, wasn't the issue. Trying to check the cocoapods now, could be related to the new update.

**Comment by giorgi-abashidze** [comment]
**now i tried it on the android emulator and app crashes when i open image picker, error is:**

System.err: java.lang.NullPointerException: Attempt to read from field ‘int android.app.Fragment.mContainerId’ on a null object reference
System.err: at android.app.BackStackRecord$1.onPreDraw(BackStackRecord.java:1131)
System.err: at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
System.err: at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
System.err: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
System.err: at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
System.err: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
System.err: at android.view.Choreographer.doCallbacks(Choreographer.java:580)
System.err: at android.view.Choreographer.doFrame(Choreographer.java:550)
System.err: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
System.err: at android.os.Handler.handleCallback(Handler.java:739)
System.err: at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: at android.os.Looper.loop(Looper.java:135)
System.err: at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: at java.lang.reflect.Method.invoke(Native Method)
System.err: at java.lang.reflect.Method.invoke(Method.java:372)
System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by giorgi-abashidze** [comment]
@ogmedia update of what? nativescript?

**Comment by giorgi-abashidze** [comment]
I think its a permissions problem

**Comment by giorgi-abashidze** [comment]
I changed my getImage to this and it worked.

```
 selected.getImageAsync((source)=>{
                    viewModel.set("selectedImage",source); 
                });
```
