### ISSUE TITLE
Platform specified in Podfile conflicts

### ISSUE THREAD

**Issue by hosikiti** [NativeScript/nativescript-imagepicker#186]
Since this plugin specifies  `platform :ios, '8.0'` in Podfile and my plugin specifies `platform :ios, '9.0'`, pod install fails on tns prepare, saying following:
```
[!] Invalid `Podfile` file: The target `Pods-myapp` already has a platform set..
```

My Podfile(excerpt) in platform/ios:
```
use_frameworks!

target "myapp" do

	# Begin Podfile - /Users/***/projects/myapp/node_modules/nativescript-imagepicker/platforms/ios/Podfile
		platform :ios, '8.0'
		pod 'QBImagePickerController', '~> 3.4.0'
	# End Podfile
	
	# Begin Podfile - /Users/***/projects/myapp/node_modules/nativescript-xz-twitter-sdk/platforms/ios/Podfile
		pod 'TwitterKit', '>= 3.3.0'
		platform :ios, '9.0'
	# End Podfile

end
```

nativescript-xz-twitter-sdk is my original plugin to use TwitterKit and it requires platform :ios, '9.0'. 
Is it possible to change platform version of this plugin from 8.0 to 9.0? So I can remove `platform` specification from my plugin. Otherwise, it would be nice if there'd be any way to resolve this conflicts.  

### Which platform(s) does your issue occur on?
- iOS 

### Please, provide the following version numbers that your issue occurs with:
- CLI: 4.0.0

Thanks.

**Comment by ramoncardena** [comment]
Same problem here with kinvey and imagepicker plugins:

```
# Begin Podfile - /Users/.../node_modules/kinvey-nativescript-sdk/platforms/ios/Podfile 
 platform :ios, '9.0'
pod 'SAMKeychain', '~> 1.5.2'
 
 # End Podfile 
# Begin Podfile - /Users/.../node_modules/nativescript-imagepicker/platforms/ios/Podfile 
 platform :ios, '8.0'

pod 'QBImagePickerController', '~> 3.4.0' 
 # End Podfile 

end
```
### Which platform(s) does your issue occur on?
iOS
### Please, provide the following version numbers that your issue occurs with:
CLI: 4.0.1

**Comment by DimitarTodorov** [comment]
Fixed with https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.2
