### ISSUE TITLE
Having some issues using getImage()

### ISSUE THREAD

**Issue by ckhordiasma** [NativeScript/nativescript-imagepicker#19]
Hello, I've been looking at trying to use this image selector for single image selections on Android, and I was having some troubles with getting an ImageSource object out of this plugin.

Using the following imports,
```
var imageSource = require('image-source');
var imagePickerModule = require("nativescript-imagepicker");
```
I have the following code which does not work. I can successfully select an image, but I can't seem to get the ImageSource object out of the function call. I have included some very basic alert calls with catch() statements to try to figure out what was going wrong. The first alert was to see what the result of context.present() was, and the JSON stringified result was 
```
[{"_observers":{}, "disableNotifications":{},"_uri":{},"_thumbRequested":false}]
```
Next, I attempted to get the ImageSource from the first picture in the array using getImage(). However, the neither the then() function nor the catch() function (Error A) ran after getImage(). I did, however, get Error B to show up, although it did not have any error message associated with it.

```
context.authorize().then(function () {
            return context.present();
         })
         .then(function (pickedPictures) {
            var size = {
               maxWidth: 100,
               maxHeight: 100
            };
            alert("Stringified pictures: " + JSON.stringify(pickedPictures));
           //displays [{"_observers":{}, "disableNotifications":{},"_uri":{},"_thumbRequested":false}]

            return pickedPictures[0].getImage(size)
               .then(function (pickedPicture) {
                  alert('Success - '  + JSON.stringify(pickedPicture));
                  return self.set('picture', pickedPicture);
               })
               .catch(function (error) {
                  alert('Error A: ' + JSON.stringify(error));
                  //This catch function does not appear.
               });
         }).catch(function (error) {
            alert('Error B: ' + JSON.stringify(error));
           //This catch function does appear, showing:
          //Error B: {}
         });;
```

Is there something I am doing wrong with my implementation of this module?

@KallynGowdy as far as I can tell, it seems like the getImage() function is null in the pickedPictures[0] object. For example, if I replaced getImage() with something nonsensical like getRabbits(), I get the same scenario, where Error A doesn't appear but Error B appears.

**Comment by KallynGowdy** [comment]
@ckhordiasma Can you tell us which version is in your `package.json`? `getImage()` was only added in `v0.0.5`, and I have confirmed that `getImage()` is present on Android in that version.

Additionally, if you have the latest version, has the `thumb` property worked for you? Because the Android implementations between `thumb` and `getImage()` are almost identical.

**Comment by NickIliev** [comment]
@ckhordiasma 

You dont need the return statement before pickedPicture[0].getImage()
For example this should work out for your scenario : 
```
	context
		.authorize()
		.then(function() {
			return context.present();
		})
		.then(function(pickedPictures) {
			pickedPictures.forEach(function(selected) {
                console.log("----------------");
                console.log("uri: " + selected.uri);           
                console.log("fileUri: " + selected.fileUri);

                selected
                    .getImage({ maxWidth: 100, maxHeight: 100})
                    .then(function(imageSource) {
                        console.log("Retrieved image: " + imageSource);
                        // use the image-source here
                    }).catch(function(e) {
                        console.log("Error: " + e);
                        console.log(e.stack);
                    });

		}).catch(function (e) {
			console.log(e);
		});
```

At the link below you will find a basic sample app demostrating how to use getImage()
[https://github.com/NativeScript/sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload)

Hope that will be useful - let me know if you need further assistance!

**Comment by ckhordiasma** [comment]
Hello, thanks @KallynGowdy and @NickIliev for your help! I was successfully able to get `thumb` earlier, but was hoping to use getImage() for more control over the size of the image received. Looking at versions, I was using the version from the telerik marketplace (v0.4), so I believe that is the issue.
