### ISSUE TITLE
Imagepicker stops working after using nativescript-mediafilepicker

### ISSUE THREAD

**Issue by surdu** [NativeScript/nativescript-imagepicker#192]
We need in our project to pick images and videos, so until this plugins supports videos also for Android we opted to use [nativescript-mediafilepicker](https://github.com/jibon57/nativescript-mediafilepicker) for videos.

The problem is that as soon as we open the video picker once, every time we try to use nativescript-imagepicker to pick an image, the [onResult method](https://github.com/NativeScript/nativescript-imagepicker/blob/90a74eff6dc9787b81e6afe2f59f51c524191a1b/src/imagepicker.android.ts#L141) is not called anymore, so the promise for `imagePickerContext.present()` will never be fulfilled.

After some investigation I realised that nativescript-mediafilepicker which uses [Android-FilePicker](https://github.com/DroidNinja/Android-FilePicker) for it's Android version, appears to be using [the same mechanism](https://github.com/DroidNinja/Android-FilePicker/blob/95216ceeeac3ea95939f6fcf0d1d18ea320d4829/app/src/main/java/vi/filepicker/MainActivity.java#L65-L84) as this plugin for opening the picker, but my restricted knowledge of Android prevented me to investigate further.

This happens on Android only.

Versions:

```
nativescript-imagepicker: 6.0.2
nativescript-mediafilepicker: 1.0.5
nativescript: 4.0.2
tns-android: 4.0.1
```

**Comment by lini** [comment]
Hi,
I did some research on this bug and found the cause. The mediafilepicker plugin incorrectly replaces a callback from the NativeScript ui frame code and prevents the original callback from running. Here is the line where this happens(https://github.com/jibon57/nativescript-mediafilepicker/blob/607d824ac5e615593cc444ed290ea1146219984e/src/mediafilepicker.android.ts#L58):

        activity.onActivityResult = function (requestCode, resultCode, data) {

There is nothing that can be done in the imagepicker plugin to fix this. I will open an issue in the other plugin with information on how to correctly handle activity results.
