### ISSUE TITLE
IOS : Selected image is empty

### ISSUE THREAD

**Issue by kefahB** [NativeScript/nativescript-imagepicker#197]
### Which platform(s) does your issue occur on?
- iOS
- emulator or device. What type of device?
Tested on : 
- IOS 10.2 on iPhone 6 
- IOS 11.4 on iPhine 8 Plus

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
4.1.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)

"tns-core-modules": "^4.1.0",

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)

"tns-android": {
			"version": "4.1.3"
		},
		"tns-ios": {
			"version": "4.1.1"
		}

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.7.1",
		"typescript": "~2.6.2"
	}

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

I use your code with onSelectSingleTap method : 

```js
private startSelection(context) {
        context
            .authorize()
            .then(() => {
                this.imageAssets = [];
                this.imageSrc = null;
                return context.present();
            })
            .then((selection) => {
                console.log("Selection done: " + JSON.stringify(selection));
                this.imageSrc = this.isSingleMode && selection.length > 0 ? selection[0] : null;

                // set the images to be loaded from the assets with optimal sizes (optimize memory usage)
                selection.forEach(element => {
                    element.options.width = this.isSingleMode ? this.previewSize : this.thumbSize;
                    element.options.height = this.isSingleMode ? this.previewSize : this.thumbSize;
                });

                this.imageAssets = selection;
            }).catch(function (e) {
                console.log(e);
            });
    }
```

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

On IOS i get this after select image : 
```js
[{"_observers":{},"_options":{"keepAspectRatio":true},"_ios":{}}]
```
It work fine on android 

Thank you

**Comment by NevinDry** [comment]
Hi,

I am using the same code and I got the **same issue with an Ipad Air IOS 11.4**.

Modules version 

"tns-core-modules": "^4.1.0",
"tns-android": {
"version": "4.1.3"
},
"tns-ios": {
"version": "4.1.1"
}
"nativescript-imagepicker": "^6.0.2",

It's working fine on Android too.

**Comment by NevinDry** [comment]
Hi,

I have done some research on this issue, and here is how I fixed it 

```
pickFile() {
        const that = this;
        that.context
            .authorize()
            .then(function () {
                return that.context.present();
            })
            .then(function (selection) {
                selection.forEach(function (selected) {
                    let file;
                    if (selected._android) {
                        file = fileSystemModule.File.fromPath(selected._android);
                        that.uploadFile(file);
                    }else{
                        imageSourceModule.fromAsset(selected).then((imageSource) => {

                        const folder = fileSystemModule.knownFolders.documents().path;
                        const fileName = "test.png"; 
                        const path = fileSystemModule.path.join(folder, fileName);
                        const saved = imageSource.saveToFile(path, "png");
                        if (saved) {
                            console.log("Image saved successfully!");
                            file = fileSystemModule.File.fromPath(path);
                            that.uploadFile(file);
                        }else{
                            //process error
                        }
                    });
                }
            });
            }).catch(function (e) {
                console.log(e);
                // process error
            });
```

You can see that first, I use the TNS imageSourceModule so don't forget to declare it at the top.

`const imageSourceModule = require("tns-core-modules/image-source");
`

I use the fromAsset function directly on the "selected" because apparently with the new version of this plugin, "selected" is an Asset. So you got an imageSource and you can use the "saveToFile" function that will copy the Asset into a new location (get this location using fileSystemModule from TNS). Use the **path** of this new location for your UI, and the image will appear. You can also create a file object from this location ( fileSystemModule.File.fromPath(path); ), I use for upload.

I can help if you need more information.

**Comment by Skintillion** [comment]
This worked for me for uploading base 64. Much simpler implementation and no file copying.

```
imagePickerContext
    .authorize()
    .then(function() {
        return imagePickerContext.present();
    })
    .then(function(selection) {
        selection.forEach(function (selected) {
            imageSourceModule
            .fromAsset(selected)
            .then((imageSource) => {
                var imageBase64 = imageSource.toBase64String("jpg",60);
                console.log(imageBase64); 
                loader.show(imageLoaderOptions);
                console.log("Post Image");
                fetch(config.apiUrl + "image", {
                        method: "POST",
                        body: JSON.stringify({
                            image: imageBase64
                        }),
                        headers: {
                        "Authorization": "Bearer " + config.token,
                        "Content-Type" : "application/json"
                        }
                    })
                .then(handleErrors)
                .then(function(response) {
                    loader.hide();
                    pageData.set("image",response._bodyText);
                    
                });
            });
        });
    }).catch(function (e) {
        console.log(e);
        
    });
```

**Comment by vignesh-web** [comment]
> Hi,
> 
> I have done some research on this issue, and here is how I fixed it
> 
> ```
> pickFile() {
>         const that = this;
>         that.context
>             .authorize()
>             .then(function () {
>                 return that.context.present();
>             })
>             .then(function (selection) {
>                 selection.forEach(function (selected) {
>                     let file;
>                     if (selected._android) {
>                         file = fileSystemModule.File.fromPath(selected._android);
>                         that.uploadFile(file);
>                     }else{
>                         imageSourceModule.fromAsset(selected).then((imageSource) => {
> 
>                         const folder = fileSystemModule.knownFolders.documents().path;
>                         const fileName = "test.png"; 
>                         const path = fileSystemModule.path.join(folder, fileName);
>                         const saved = imageSource.saveToFile(path, "png");
>                         if (saved) {
>                             console.log("Image saved successfully!");
>                             file = fileSystemModule.File.fromPath(path);
>                             that.uploadFile(file);
>                         }else{
>                             //process error
>                         }
>                     });
>                 }
>             });
>             }).catch(function (e) {
>                 console.log(e);
>                 // process error
>             });
> ```
> 
> You can see that first, I use the TNS imageSourceModule so don't forget to declare it at the top.
> 
> `const imageSourceModule = require("tns-core-modules/image-source"); `
> 
> I use the fromAsset function directly on the "selected" because apparently with the new version of this plugin, "selected" is an Asset. So you got an imageSource and you can use the "saveToFile" function that will copy the Asset into a new location (get this location using fileSystemModule from TNS). Use the **path** of this new location for your UI, and the image will appear. You can also create a file object from this location ( fileSystemModule.File.fromPath(path); ), I use for upload.
> 
> I can help if you need more information.

Hi I have same issue. I was not able to get full image information in IOS like filepath, filename and size. Please help me.

**Comment by coderaven** [comment]
> This worked for me for uploading base 64. Much simpler implementation and no file copying.
> 
> ```
> 
> var imageSourceModule = require("tns-core-modules/image-source");
> var imagepicker = require("nativescript-imagepicker");
> var imagePickerContext = imagepicker.create({ mode: "single" });
> ```
> 
> ```
> imagePickerContext
>     .authorize()
>     .then(function() {
>         return imagePickerContext.present();
>     })
>     .then(function(selection) {
>         selection.forEach(function (selected) {
>             imageSourceModule
>             .fromAsset(selected)
>             .then((imageSource) => {
>                 var imageBase64 = imageSource.toBase64String("jpg",60);
>                 fetch(config.apiUrl + "image", {
>                         method: "POST",
>                         body: JSON.stringify({
>                             image: imageBase64
>                         }),
>                         headers: {
>                         "Authorization": "Bearer " + config.token,
>                         "Content-Type" : "application/json"
>                         }
>                     })
>                 .then(handleErrors)
>                 .then(function(response) {
>                     //Do something when done.
>                 });
>             });
>         });
>     }).catch(function (e) {
>         console.log(e);
>         
>     });
> ```

Uploading in base64 works easiest, yes - but it does have some limitations in terms of speed as it gets quite slow as soon as the image gets bigger.

**Comment by avishbansal2** [comment]
ERROR Error: Uncaught (in promise): Asset '/storage/emulated/0/DCIM/Restored/IMG_20200115_103131.jpg' cannot be found.

Please tell me how to resolve this error?

**Comment by skmani** [comment]
i am also having the same issue any fixes.
