### ISSUE TITLE
Quick question: Thumbnail Layout

### ISSUE THREAD

**Issue by patuku-roy** [NativeScript/nativescript-imagepicker#20]
Hi,

Do we have any method to override the default thumbnail layout without forking this repository? Because I'm looked at the source code file and did not found any options or method that can expose this functionality.

**Comment by patuku-roy** [comment]
Okay, I ended with copying the whole project and treat as a regular views so I can redirect to the right page after finish selection using `goBack()` function. And of course I can play with the layout very easy. I just miss one thing on ios at least, which is I have to cache all thumbnails using `image-cache` module because the page very damn slow when loading if we have to generate all thumbnails every time we open the selection page

**Comment by PanayotCankov** [comment]
Ths slow page is because the plugin uses repeater and it realizes all images. If it used UICollectionView probably it would be better. We can consider using some of the available {N} plugins that wrap the UICollectionView for {N} and rewrite just that piece of UI in the plugin.

**Comment by patuku-roy** [comment]
@PanayotCankov how about if we use the NS UI `RadListView`? there is `ListViewGridLayout` we can use to represent those images and CMIIW but the `RadListView` is using `UICollectionView` isn't it? and of course, I still believe if we cache the thumbnails then the whole performance will increase.

**Comment by PanayotCankov** [comment]
You are correct, we will have to avoid caching the thumbs.

If we use virtualization well the iOS will provide thumbs when possible eventually caching them.
There is a relatively new method `getImage({ width? height? }): Promise<ImageSource>` that can produce just the right thumb for us. These don't get cached.

In the long terms the best options would be if the {N} Image view can consume instances that have "getImage" for its `src` and provide the layout width and height arguments. That way the size of the Image will get directly to the PHAssets and the PH will return a properly sized thumb from the PH framework, letting the PH framework do the caching. Does that make sense?

**Comment by patuku-roy** [comment]
@PanayotCankov that's a make sense and I will try to implement using `UICollectionView` or maybe `GridView` instead and will see the performance is.

**Comment by patuku-roy** [comment]
@PanayotCankov do you have any idea how to make images generate per paging rather than generate all at once? I have some thought to load thumbnails gradually rather than generate all at the same time.

**Comment by PanayotCankov** [comment]
@patuku-roy Excellent. If the performance is better, we would love to see a PR :)

**Comment by patuku-roy** [comment]
@PanayotCankov I will try to do PR after my tight deadline ... hoping soon ...
