### ISSUE TITLE
Change message when requesting permission to access photos

### ISSUE THREAD

**Issue by miguelopezv** [NativeScript/nativescript-imagepicker#204]
I've submitted my app to the App Store and they're asking to change the message that appears the first time you use the camera, and instead display a message that explains why are you requesting access to the camera or what are you going to do with the photo. How can I change this message?

**Comment by DimitarTodorov** [comment]
Hi @miguelopezv ,

You can manually set the message in your project's info.plist file

**app/App_Resources/iOS/Info.plist**

`<key>NSCameraUsageDescription</key>`
`<string>camera description.</string>`

**Comment by fthuin** [comment]
I also had my app rejected today because of this. This should be somewhere in the docs 👍

**Comment by lini** [comment]
Thanks for the feedback. Docs will be updated - #226
