### ISSUE TITLE
image to base64 string

### ISSUE THREAD

**Issue by yonkoGH** [NativeScript/nativescript-imagepicker#206]
Hi 
Lately I'm facing a problem converting the images to base64 string in both platforms 
the weird thing is that i got different results from ios and android and both strings are shorts

- Both platforms
- 4.2.0/4.2.0
- emulator
- CLI: 4.2.0
- Cross-platform modules: ^4.2.0
- Runtime(s): 4.2.0
- Plugin(s): ^6.0.3

#code 
`context
            .authorize()
            .then(() => {
                return context.present();
            })
.then((selection) => {
                fromAsset(selection[0]).then(res => {
                    console.log(res.toBase64String("jpeg"));
                });
`

any suggestions ??  much appreciated ..

**Comment by NickIliev** [comment]
@yonkoGH the thing is that `console.log` will truncate long logs differently on iOS and Android but ni fact. the base64 string is actually the same. For example, for test purposes you could directly print the base64 string to see the actual output (as done [here](url
https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-imagepicker/issue-206))

**Comment by yonkoGH** [comment]
ok tnx
