### ISSUE TITLE
Angular : Imagepicker in modal

### ISSUE THREAD

**Issue by hiddencaliber** [NativeScript/nativescript-imagepicker#214]
Please provide an example for Angular implementation:-

The **hostView** parameter can be set to the view that hosts the image picker. Applicable in iOS only, intended to be used when open picker from a modal page.

**Comment by DimitarTodorov** [comment]
Issue is addressed in the latest release of ImagePicker:
https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.6
