### ISSUE TITLE
Is SelectedAsset.fileUri still a thing?

### ISSUE THREAD

**Issue by aspidites** [NativeScript/nativescript-imagepicker#22]
When ever I try to access `fileUri`, nothing happens. It seems to be the case that any erroneous lines of javascript fail silently, so I don't have any good indication of what I'm doing wrong. I've attempted to attach a debugger, but that only results in white screen. Here's what I'm attempting:

```javascript
var impagePicker = require("nativescript-imagepicker");
var context = impagePicker.create({mode: 'single'});
context.authorize()
    .then(function() {
        return context.present();
    })
    .then(function(selection) {
        selection.forEach(function(selected) {
            console.log(selected.uri);
            console.log(selected.fileUri);
        });
    });
```

`uri` prints a `content://` url, and `fileUri` prints nothing at all. In fact, attempting to do *anything* with `fileUri` fails.

I've attempted this on a OnePlus X (Android 5.1.1) using nativescript-image-picker 0.0.6, tns-android 2.0.0, and tns-core-modules 2.0.1. I have *not* tried this on any form of IOS device. I'm hoping I'm missing something obvious.

**Comment by Daxito** [comment]
Check #25 , it has some code how to get the image source instead.
