### ISSUE TITLE
how to save selected video files to app directory?

### ISSUE THREAD

**Issue by mbelaj** [NativeScript/nativescript-imagepicker#220]
Hi,

I know how to save selected images to some app folder but I can't find how to do the same with video (mp4) files. Can you help me please? 

Best regards
Mladen Belaj

**Comment by ehibes** [comment]
I found how to copy a video using `tns-core-modules/file-system`. It would be nice to integrate this on the demo app maybe...

```
var fs = require("tns-core-modules/file-system");

const path = '/path/to/your/file.MOV';

const videoFile = fs.File.fromPath(path);
const documents = fs.knownFolders.documents();
var targetFile = documents.getFile('video-copy.MOV');

const binarySource = videoFile.readSync((err) => {
  console.log(err);
});
targetFile.writeSync(binarySource, (err) => {
  console.log(err);
});
```

**Comment by mbelaj** [comment]
I solved with next solution:

import * as fs from "tns-core-modules/file-system";
import { getFile } from "tns-core-modules/http";
import { File } from "tns-core-modules/file-system";

    pickVideos(number): Promise<any> {
        return new Promise(function (resolve, error) {
            let mode = "multiple";
            if (number == 1) {
                mode = "single";
            }
            let context = filePicker.create({
                mode: mode,
                mediaType: ImagePickerMediaType.Video
            });
            context.authorize().then(() => {
                return context.present();
            }).then((selection) => {
                let slike = [];
                let new_path = fs.path.join(fs.knownFolders.documents().path, "my_folder");
                let folder = fs.Folder.fromPath(new_path);
                for (let i = 0; i < selection.length; i++) {

                    const selected = selection[i];
                    const ios = selected.ios;

                    if (ios) {
                        const opt = PHVideoRequestOptions.new();
                        opt.version = PHVideoRequestOptionsVersion.Current;

                        PHImageManager.defaultManager().requestAVAssetForVideoOptionsResultHandler(
                            ios, opt, (asset: AVAsset, audioMix: AVAudioMix, info: NSDictionary<any, any>) => {
                                let regex = /(file[^>]*)/g
                                let file = asset.toString().match(regex)[0];
                                let filename = (new Date).getTime().toString() + ".mp4";
                                let new_path = fs.path.join(fs.knownFolders.documents().path, "PDI");
                                let folder = fs.Folder.fromPath(new_path);
                                let path = fs.path.join(folder.path, filename);
                                getFile(file, path).then((resultFile: File) => {

                                }, (e) => {
                                });
                                slike.push(path);
                                if (i == selection.length - 1) {
                                    resolve(slike);
                                }

                            });
                    }

                };
            }, (err) => {
                console.log("error " + err);
                resolve([]);
            });
        })
    }

**Comment by erkanarslan** [comment]
This does not work in NS6
