### ISSUE TITLE
Image selected is empty

### ISSUE THREAD

**Issue by Mflm** [NativeScript/nativescript-imagepicker#221]
Hi all

I have a problem to upload an image in firebase.
I select an image and later I upload to firebase, in Android works well but in iOS, the image have 0 bytes.
Why?

**context
    .authorize()
    .then(function() 
	{
        return context.present();
    })
    .then(function(selection) 
	{
        selection.forEach(function(selected) 
		{
                         var logoPath = appPath + selected.ios;
                         var childRef = storageRef.child(namefile);
			childRef.put(fs.File.fromPath(logoPath)).then
			(
			uploadedFile =>
			{
                             //HERE I Upload the file.
                         }
			,error => 
			{
			console.log("firebase.doWebUploadFile error: " + error);
			}
			);
        });
    }).catch(function (e) {
		console.log(e);
    });**
	
Thanks

**Comment by tsonevn** [comment]
Hi @Mflm,
You can try making a local copy of the image using the [ImageSource module](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/app/ns-framework-modules-category/image-source/save-image/save-image-page.js#L49-L67) and using it for uploading the image in Firebase.

**Comment by Mflm** [comment]
Thanks @tsonevn 

This works.
