### ISSUE TITLE
iOS: Should resolve after modal has dismissed

### ISSUE THREAD

**Issue by mailiam** [NativeScript/nativescript-imagepicker#236]
Is there any particular reason that `imagePicker.present()` is resolved before dismissing?

Complicated modal chaining (ie. showing `ImageCropper` after `imagePicker.present()` in modal) is broken because QBImagePicker is not dismissed when resolved.

_below example and error is just to represent process_

## example

```ts
// currently in modal 

async getCroppedImage() {
  const context = imagepicker.create();
  await context.authorize();
  const selections = await context.present();
  selections.forEach((selection) => {
    selection.getImageAsync(async source => {
      const imageSource = new ImageSource();
      imageSource.setNativeSource(source);
      const cropper = new ImageCropper();
      const cropped = await cropper.show(imageSource); // Error in this line
    });
  });
}

```

## error 

```
Warning: Attempt to present <TOCropViewController: 0x1059b0200> on < QBImagePickerController: 0x105839c00> whose view is not in the window hierarchy!
```

## possible fix

I could fix below error by moving https://github.com/NativeScript/nativescript-imagepicker/blob/0e34f315d360b638bfac2185b500889561dd9088/src/imagepicker.ios.ts#L103
to 

```ts
        imagePickerController.dismissViewControllerAnimatedCompletion(true, () => {
           this._resolve(assets);

            // FIX: possible memory issue when picking images many times.
            // Not the best solution, but the only one working for now
            // https://github.com/NativeScript/nativescript-imagepicker/issues/222
            setTimeout(utils.GC, 200);
        });
```

**Comment by zbranzov** [comment]
Hi @mailiam,
Do you have a sample app (maybe modified one from the repo or created in https://play.nativescript.org/) that reproduces your case? Also, the log you have post seems more like a  warning than an error.

**Comment by zbranzov** [comment]
Hi @mailiam ,
Can you provide some details about what made you move from NativeScript to pure native development? We will be grateful to get your valuable feedback.
Thank you.

**Comment by erkanarslan** [comment]
I have this problem now.

`Attempt to present <TOCropViewController: 0x105800800> on <UIImagePickerController: 0x105013e00> whose view is not in the window hierarchy!`
