### ISSUE TITLE
How to load the actual image with URI?

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/nativescript-imagepicker#25]
How can I actually use this URI with image.imageSource ??

URI what I get look like: "content://com.android.providers.media.documents/document/image%3A34" and so on.

**Comment by Daxito** [comment]
Use something like this to get the image source.

if (app.android) {
                        var REQUIRED_SIZE = {
                            maxWidth: 800,
                            maxHeight: 800
                        };
                        var ms = selected.decodeUri(selected._uri, REQUIRED_SIZE);

                        imageTagInXML.imageSource = ms;
                    } else {

                        selected.getImage().then(function (ms) {
                            imageTagInXML.imageSource = ms;
                        })

                    }

**Comment by PanayotCankov** [comment]
Use getImage(): https://github.com/NativeScript/nativescript-imagepicker/blob/release/source/imagepicker.d.ts#L45

**Comment by PanayotCankov** [comment]
@Daxito getImage should work for both platforms. We'll make sure to add some tests and example code in the https://github.com/NativeScript/sample-ImageUpload demo app.
