### ISSUE TITLE
iOS: Sometimes in production the image picker does not close when tapping cancel or selecting an image

### ISSUE THREAD

**Issue by reinaldorauch** [NativeScript/nativescript-imagepicker#258]
When I open the picker in iOS when the app is in test flight in a "staging" environment (testing environment with production settings), the user cannot close the picker when tapping Cancel or can't even select an image from the list.

### Which platform(s) does your issue occur on?
- iOS
- iOS 12.1.3
- iPhone 6s 128gb

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.2
- Cross-platform modules: 5.2.0
- Runtime(s): Android and iOS: 5.2.0
- Plugin(s): 
```json
{
    "dependencies": {
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "nativescript-background-http": "^3.4.0",
    "nativescript-camera": "^4.2.0",
    "nativescript-imagepicker": "^6.1.0",
    "nativescript-intl": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.4.0",
    "nativescript-masked-text-field": "^4.0.1",
    "nativescript-modal-datetimepicker": "^1.1.12",
    "nativescript-plugin-firebase": "^7.7.0",
    "nativescript-pulltorefresh": "^2.2.0",
    "nativescript-social-share": "^1.5.1",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "~1.0.4",
    "query-string": "^6.2.0",
    "tns-core-modules": "^5.2.0",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/chai": "^4.1.7",
    "@types/mocha": "^5.2.6",
    "@types/node": "^11.9.4",
    "@types/query-string": "^6.2.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "eslint": "^5.14.1",
    "eslint-plugin-json": "^1.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-appium": "^5.0.0",
    "nativescript-dev-typescript": "^0.8.0",
    "nativescript-dev-webpack": "^0.19.2",
    "tslint": "^5.12.1",
    "typescript": "^3.3.3"
  }
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the imagePicker with this function:
```typescript
async function createPicker(): Promise<ImageAsset> {
    const c = imagePicker.create({ mode: 'single' });
    await c.authorize();
    const [ img ] = await c.present();
    return img;
}
```
And prepare the project with tns prepare ios --release --build --clean 
And then send the build for testing in TestFlight in apple app store

### Is there any code involved? 
will post and test app soon

**Comment by tbozhikov** [comment]
Hi @reinaldorauch,

This looks the same as [this issue](https://github.com/NativeScript/nativescript-imagepicker/issues/251). Could you please try your app with the latest version ([v6.1.2](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.1.2)) and let us know if the issue persists?

Thanks!

**Comment by reinaldorauch** [comment]
Hello, will try that, thanls @tbozhikov

**Comment by reinaldorauch** [comment]
@tbozhikov that fixed the issue, thanks. Will close this as it is resolved.
