### ISSUE TITLE
Get Image name and date taken - nativescript-imagepicker

### ISSUE THREAD

**Issue by praveen-wal** [NativeScript/nativescript-imagepicker#261]
### Which platform(s) does your issue occur on?

iOS - Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) ------ 5.3.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) ------ 5.3.1
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) . ------  5.0.0
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

----- "nativescript-imagepicker": "^6.1.2",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

When uploading an image using nativescript-imagepicker. How can I get the image details as in Name and details like when the image was taken?

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

```
context
    .authorize()
    .then(function() {
      return context.present();
    })
    .then(selection => {
      selection.forEach(selected => {
        if (selected._android) {
          file = fileSystemModule.File.fromPath(selected._android);
          //viewModel.uploadFile(file);
        } else {
          imageSourceModule.fromAsset(selected).then(imageSource => {
            this.images.push(imageSource);
            const folder = fileSystemModule.knownFolders.documents().path;
            const fileName = "Photo.png";
            const path = fileSystemModule.path.join(folder, fileName);
            const saved = imageSource.saveToFile(path, "jpg", 60);

          });
        }
      });
    })
    .catch(function(e) {
      console.log("error in selectPicture", e);
    });
```

**Comment by NickIliev** [comment]
@praveen-wal this would be possible only if the image has stored metadata (for example EXIF data). Then to achieve that, you will need a native approach - see [this blog post ](https://medium.com/@maximbilan/exif-how-to-get-exif-data-in-ios-2a28af63eaac)for how to extract metadata from UIImage (of course you will need to get a reference to the UIImage and use the [NativeScript code conversion](https://docs.nativescript.org/core-concepts/ios-runtime/Marshalling-Overview)).
