### ISSUE TITLE
Error new update the nativescript 

### ISSUE THREAD

**Issue by adrianlaraperez88** [NativeScript/nativescript-imagepicker#27]
Error new update the nativescript

**Comment by PanayotCankov** [comment]
Could you elaborate on the problems? Are you upgrading to new nativescript version and after upgrade the plugin fails?

**Comment by adrianlaraperez88** [comment]
yes this is the problem

**Comment by PanayotCankov** [comment]
What are the errors? Does the app even launch? Or after launch there is a point where it fails? Is there some output you may provide so I can investigate it further?

**Comment by adrianlaraperez88** [comment]
When I run a run android after installation fails, and so I read it is by using java function deprecated.

**Comment by adrianlaraperez88** [comment]
Same problem antonio.nodal88@gmail.com, send you an email.
basicly deprecated api usage, android platform
