### ISSUE TITLE
iOS file path is never returned

### ISSUE THREAD

**Issue by ibnYusrat** [NativeScript/nativescript-imagepicker#284]
Hi,

While the image does show up in the demo app, the object returned after selection doesn't contain the file path on iOS

This is the object I get:

`{
"_observers": {},
"_options": {
"keepAspectRatio": true,
"autoScaleFactor": true
},
"_ios": {}
}
`

on Android, the `_android` property contains the path to the selected image. 

I need it to upload user's profile photo to firebase. Can someone please suggest what am I doing wrong here?

**Comment by tgpetrov** [comment]
@ibnYusrat 
This has been commented on several issues. The library used for iOS doesn't provide us with a path that we can use. You can see some suggestions how to proceed here and here.

The reason there is no path is that the library we are using on iOS returns an asset which contains no path. As this has been commented on a few different thread, here are some suggestions how to proceed: [idea 1](https://github.com/NativeScript/nativescript-imagepicker/issues/197#issuecomment-400560349) and [idea 2](https://github.com/NativeScript/nativescript-imagepicker/issues/181#issuecomment-384585293)
