### ISSUE TITLE
mediaType enum is not exported

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-imagepicker#285]
### Make sure to check the demo app(s) for sample usage 
**Done**

### Make sure to check the existing issues in this repository 
**Done**

### If the demo apps cannot help and there is no issue for your problem, tell us about it
There is a ImagePickerMediaType enum that seems like it can be added to the [demo app](https://github.com/NativeScript/nativescript-imagepicker/blob/master/demo/app/main-view-model.ts#L71):
```
let context = imagepicker.create({ mode: "single", mediaType: imagepicker.ImagePickerMediaType.Image });
```
However when I run the app, it crashes with` Cannot read property 'Image' of undefined`

### Which platform(s) does your issue occur on?
- iOS/Android/**Both** 
- iOS/Android versions **any**
- emulator or device. What type of device? **both**

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) **6.0.2**
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) **6.0.0**
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) **6.0.0**
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Go to demo app and replace this line:
```
let context = imagepicker.create({ mode: "single" });
```
with:
```
let context = imagepicker.create({ mode: "single", mediaType: imagepicker.ImagePickerMediaType.Image });
```
Run the app and tap the PICK SINGLE button. 

expected: app to work same as before change
actual: app crashes

**Comment by zbranzov** [comment]
The fix is published in nativescript-imagepicker@6.3.0
