### ISSUE TITLE
no static field with name='EXTRA_MIME_TYPES'

### ISSUE THREAD

**Issue by erss400** [NativeScript/nativescript-imagepicker#295]
Hey,

When I run my project with:

tns run android --build

I get the following error.

`[Error: java.lang.NoSuchFieldError: no static field with name='EXTRA_MIME_TYPES' signature='Ljava/lang/String;' in class Landroid/content/Intent;
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
JS:     com.tns.gen.java.lang.Object_vendor_82084_26_ClickListenerImpl.onClick(Object_vendor_82084_26_ClickListenerImpl.java:18)
JS:     android.view.View.performClick(View.java:4452)
JS:     android.widget.Button.performClick(Button.java:148)
JS:     android.view.View$PerformClick.run(View.java:18428)
JS:     android.os.Handler.handleCallback(Handler.java:725)
JS:     android.os.Handler.dispatchMessage(Handler.java:92)
JS:     android.os.Looper.loop(Looper.java:176)
JS:     android.app.ActivityThread.main(ActivityThread.java:5365)
JS:     java.lang.reflect.Method.invokeNativ...`

Here is my package.json

`{
  "name": "zokdak-master",
  "version": "1.0.0",
  "description": "zokdak",
  "author": "zokdak <zokdak@zokdak.com>",
  "license": "MIT",
  "nativescript": {
    "id": "com.zokdak.master",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.1"
    }
  },
  "dependencies": {
    "@vue/devtools": "^5.0.6",
    "axios": "^0.19.0",
    "moment": "^2.24.0",
    "nativescript-feedback": "^1.3.10",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-imagepicker": "^7.0.0",
    "nativescript-plugin-firebase": "^9.0.4",
    "nativescript-socketio": "^3.2.1",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-toasty": "^1.3.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.2.0",
    "net": "^1.0.2",
    "numeral": "^2.0.6",
    "tns-core-modules": "6.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "1.0.1",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
}
`

**Comment by DimitarTodorov** [comment]
Hi, @erss400 

We tested the demo-vue from the repo of the plugin with latest versions and it seems it is working correctly and we cannot observe the error you point here. Also note that in the command `tns run android --build` the `--build` flag is not supported operation by {N} CLI. Can you please provide a code example or a sample app with more detailed information about what You are trying to do and steps to reproduce the error.

**Comment by erss400** [comment]
Sorry it seems to be the android version. It's working on a higher android version.
