### ISSUE TITLE
Launch timeout has expired, giving up wake lock!

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-imagepicker#31]
When I click on an image in imagepicker it never gets back to the app. I get black screen on the emulator and nothing happens no matter how long I wait. The adb logcat shows this: "Launch timeout has expired, giving up wake lock!". Any advise please why it happens?

My config:
nativescript-imagepicker: 0.0.6
tns-ios: 2.3.0
tns-android: 2.3.0
tns-core-modules: 2.3.0

**Comment by PanayotCankov** [comment]
What emulator are you using? Is it the Android SDK one or Geny etc? What API level does it run on?
