### ISSUE TITLE
When trying to compile, I get error TS2304: Cannot find name 'NSData'

### ISSUE THREAD

**Issue by Stardock-AI** [NativeScript/nativescript-imagepicker#313]
Trying to run the demo app from the NativeScript Playground and running into missing ios.d types.
I can see the specifications in node_modules\tns-platform-declarations\ios\objc-x86_64, but maybe there is a missing reference?

Here is my sample app I am trying to run.
https://github.com/Stardock-AI/ImagePicker-httpUpload

Here is the original Playground app.  I upgraded the file-system libraries to include the lastest NS 6.1 libs.

![FilePickerErrors](https://user-images.githubusercontent.com/51218987/68166696-bf041000-ff28-11e9-88ad-27504ad11849.png)

https://play.nativescript.org/?template=play-ng&id=pmXu7c&v=15

**Comment by EddyVerbruggen** [comment]
Closed by https://github.com/Stardock-AI/ImagePicker-httpUpload/pull/1

**Comment by Stardock-AI** [comment]
Thank you Eddy!  You are the best!!

**Comment by Skillnter** [comment]
Hi,

I am unable to fix the same issue. Can you explain, how is this resolved? What steps should I follow to fix this?

**Comment by assemnabill** [comment]
I have the same issue. what was the solution?

**Comment by n-sri** [comment]
What is the solution to this error? Above link gives 404 error.

**Comment by n-sri** [comment]
Declaring  a variable as "declare var  NSData: any;" helps building  the application without above error. It is like tricking typescript to compile successfully.
