### ISSUE TITLE
Error in reading bitmap - EACCES (Permission denied)

### ISSUE THREAD

**Issue by covbradley** [NativeScript/nativescript-imagepicker#315]
Hi All.

I've downloaded the demo app and am running the demo-angular version on an android emulator. Everything is fine until I select the image(s) and I get the following JS...

JS : Selection done: [{"_observers":{},"_options":{"keepAspectRatio":true,"autoScaleFactor":true},"_android":"/storage/emulated/0/DCIM/Camera/IMG_20191107_142608.jpg"}]

JS: Error in reading bitmap - java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_20191107_142608.jpg: open failed: EACCES (Permission denied)

I've read somewhere that it may be something to do with the permissions in the AndroidManifest.xml file (in \app\App_Resources\src\main) and to make sure that the following are set...

<manifest ...>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
</manifest>

But these are set ok.

Any ideas?

Thanks in advance.

- ====================================================
- Platform : android
- Emulator : Nexus 4 API 29
- CLI Version : 6.1.2
- Cross-platform modules : 6.2.1
- Project "package.json" : 

{
  "nativescript": {
    "id": "org.nativescript.imagepickerdemoangular",
    "tns-ios": {
      "version": "6.2.0"
    },
    "tns-android": {
      "version": "6.2.0"
    }
  },
  "dependencies": {
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "nativescript-angular": "~8.20.0",
    "nativescript-imagepicker": "../src",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "0.7.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^6.0.0"
  },
  "devDependencies": {
    "jasmine-core": "^2.5.2",
    "karma": "4.1.0",
    "karma-jasmine": "2.0.1",
    "karma-nativescript-launcher": "^0.4.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-webpack": "^1.3.0",
    "tns-platform-declarations": "^6.0.0",
    "tslint": "~5.11.0",
    "zone.js": "^0.8.4",
    "typescript": "~3.5.3",
    "karma-webpack": "3.0.5",
    "@angular/compiler-cli": "8.2.0",
    "@ngtools/webpack": "8.2.0"
  },
  "scripts": {
    "build.plugin": "cd ../src && npm run build",
    "ci.tslint": "npm i && tslint --config '../tslint.json' 'app/**/*.ts' --exclude '**/node_modules/**'",
    "ci.android.build": "npm run build.plugin && tns build android",
    "ci.ios.build": "npm run build.plugin && tns build ios",
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

**Comment by covbradley** [comment]
After trying a few things, it ended up I needed the following in my AndroidManifest.xml file...

<application
	android:requestLegacyExternalStorage="true"

as well as

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

On top of that, I've also asked for permission using the permissions plugin in my ts file...

const permissions = require("nativescript-permissions");

permissions.requestPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE, "I need these permissions because I'm cool")
            .then( () => {
                console.log("Woo Hoo, I have the power!");
            })
            .catch( () => {
                console.log("Uh oh, no permissions - plan B time!");
            });

It's also worth checking that your app has permissions by going...

Settings > Apps & Notifications > Your App > Permissions > Storage

and make sure it's allowed.

I hope that helps anyone else who gets the same problems.

Cheers.

**Comment by DarioDomiDE** [comment]
Thanks @covbradley I had the same problem. Needed to run `permissions.requestPermission` Plugin on top of this imagepicker-plugin to get permissions correctly on all android devices (most of them (but not all) worked fine without this additional plguin)

**Comment by Skillnter** [comment]
> After trying a few things, it ended up I needed the following in my AndroidManifest.xml file...
> 
> <application
> android:requestLegacyExternalStorage="true"
> 
> as well as
> 
> ```
> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> ```
> 
> On top of that, I've also asked for permission using the permissions plugin in my ts file...
> 
> const permissions = require("nativescript-permissions");
> 
> permissions.requestPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE, "I need these permissions because I'm cool")
> .then( () => {
> console.log("Woo Hoo, I have the power!");
> })
> .catch( () => {
> console.log("Uh oh, no permissions - plan B time!");
> });
> 
> It's also worth checking that your app has permissions by going...
> 
> Settings > Apps & Notifications > Your App > Permissions > Storage
> 
> and make sure it's allowed.
> 
> I hope that helps anyone else who gets the same problems.
> 
> Cheers.

Been trying to get this work but nothing is working. Please help me..

**Comment by zghotlawala** [comment]
Nope is it still not working for NS running on 6x versions... Any suggestion?
