### ISSUE TITLE
Plugin is not working in IOS simulator or in device

### ISSUE THREAD

**Issue by hasimnbvcxZ** [NativeScript/nativescript-imagepicker#33]
I have recently used this plugin. Its crashes in IOS emulator and device. following is the package configuration. I have used the plugin as in the example.

{
  "description": "Test Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "BSL Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.test",
    "tns-ios": {
      "version": "2.2.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "nativescript-angular": "^0.3.0",
    "nativescript-bluetooth": "^1.1.2",
    "nativescript-i18n": "0.0.6",
    "nativescript-imagepicker": "0.0.6",
    "reflect-metadata": "^0.1.5",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "2.2.1",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
}

following is the error on simulator,

com.apple.CoreSimulator.SimDevice.DCF7E52F-0A11-40ED-9090-9AE95E5A6925.launchd_s
im[6072](UIKitApplication:org.nativescript.test2.bsl[0x8d8d][7318]): Service exited due to signal: Segmentation faul

**Comment by xerotolerant** [comment]
Have you tried removing the platform and deleting the app from the device before re building?

**Comment by PanayotCankov** [comment]
We found some issues with some of the emulator architectures. iOS can not unwind the stack on objective-c exceptions and sometimes the file urls point a path that the app has no permissions to. Running the app on 32 bit emulator outputs the exception message but on 64 bit one it dies in pain and agony with segfault. You can try to open the project in Xcode by opening the platform/ios/<my-name.xcproj>, put breakpoint on objc_exception_throw (http://stackoverflow.com/questions/8122375/breakpoint-on-exceptions-equivalent-of-gdbs-catch-throw) and if the app hits the breakpoint use in the lldb `po $arg1` to get the exception message.
