### ISSUE TITLE
Plug-in does not work in NativeScript 8

### ISSUE THREAD

**Issue by Synax42** [NativeScript/nativescript-imagepicker#337]
When attempting to use this plug-in with NativeScript 8, once you add an import or require pointing to this plug-in 3 errors are thrown when compiling for Android and 8 for iOS all relating to core nativescript modules.

Platforms: Both
NS/Android: 8.0.0
NS/iOS: 8.0.0

Device: Android S7, iPhone 7

- CLI: 8.01
- Cross-platform modules: 8.0.0
- Runtime(s): 8.0.0 for both
- Plugin(s): 7.0.1

Pull any of the NativeScript 8 templates, install the imagepicker plugin and attempt to reference the plugin on any page and run the app.

I have attempted to reference it both ways:
var imagepicker = require("nativescript-imagepicker");
import * as imagepicker from "nativescript-imagepicker";

**Comment by Sarfaraaz** [comment]
You'll want to use this instead for NS7 and beyond.
https://www.npmjs.com/package/@nativescript/imagepicker

**Comment by Synax42** [comment]
Thank you so much, and sorry I didn't see that.... I blame having an 8 month old haha. I just didn't notice the addition of the @ in posts. Thanks again.
