### ISSUE TITLE
Question: SelectedAsset.thumb property.

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-imagepicker#36]
Find there is SelectedAsset.thumb property but couldn't get it work. Not sure if I missed anything. Could you kindly to provide sample of using SelectedAsset.thumb.

Regards

**Comment by PanayotCankov** [comment]
This: https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.xml#L6
Binds to this: https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L114
