### ISSUE TITLE
Possible to have cropped image.

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-imagepicker#37]
Is it possible to return cropped image? For example, if I have image 640x480, I wanted to return center (or specified area) of ie 300x300. 

Note: When I specify only maxWidth as option, the gallery hang.

**Comment by tsonevn** [comment]
Hi @ryc16,
For your case you could use `nativescript-imagecropper` that provides such a functionality.
Hope this helps.

**Comment by PanayotCankov** [comment]
Provide maxWidth, maxHeight from this interface https://github.com/NativeScript/nativescript-imagepicker/blob/master/nativescript-imagepicker/index.d.ts#L4 to the getImage here: https://github.com/NativeScript/nativescript-imagepicker/blob/master/nativescript-imagepicker/index.d.ts#L43 and then crop the image using the image cropper.
