### ISSUE TITLE
Crashing on iOS when album in camera roll has alot of images

### ISSUE THREAD

**Issue by bnussey** [NativeScript/nativescript-imagepicker#38]
This plugin crashes on iOS when you go to the camera roll and choose the album `All Photos` if there is a large amount of photos (Mine has 3640 photos, so assume this would also crash if another album had a lot of photos). The exact behavior is it freezes when first selecting the album, then eventually loads it and then exits from the app. Nothing is shown in the logs. However it works when I choose `Recently Added` that only has 8, it works as expected. 

Package.json has `"nativescript-imagepicker": "^2.3.1",`

My code is as follows:

```
 var context = imagepicker.create({
            mode: "single"
        });
        context.authorize()
            .then(() => {
                return context.present();
            })
            .then((selection) => {
                selection.forEach((selected) => {
                     console.log("selected", selected);
                        }).catch((err) => {
                            console.log("Error", err);
                        });
                    }
                });
            }).catch((e) => {
                console.log(e);
            });
```

**Comment by bnussey** [comment]
I've also tried to do this exact same thing on the sample project - `sample-ImageUpload` and it takes a very long time to load, performs very poorly and results in a crash as well.

**Comment by PanayotCankov** [comment]
We are about to publish a new version that will use the free collection view controller from the nativescript-telerik-ui wrapper. It will use virtualization in contrast with the current Repeater so there should be a noticeable improvement.
