### ISSUE TITLE
Missing License File...

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-imagepicker#4]
What license is this under?

**Comment by PanayotCankov** [comment]
Thanks for the notice. The plugin will be released under `Apache-2`. I will publish new version with the license attached in a while. Meanwhile If `Apache-2` is an issue we 'd like to hear your concerns.

**Comment by NathanaelA** [comment]
No, I just want to be able to put something on the http://nativescript.rocks/plugins list.
