### ISSUE TITLE
Couldn't find a way to get the actual image with this plugin

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/nativescript-imagepicker#5]
Couldn't find a way to get the actual image with this plugin

When I try to access the fileUri the system throws the following error:
'android.permission.READ_EXTERNAL_STORAGE,'

Also, the data() method is not implemented. What is the best way to get the actual image using this plugin? Can you help me?

**Comment by mcxolani** [comment]
Same here, No luck, I can only get the thumb image which is very small and low quality.

**Comment by PanayotCankov** [comment]
I think you can add permissions to read external storage in the `app/App_Resources/android/AndroidManifest.xml`.

For example you can check the [manifest of our examples](https://github.com/NativeScript/nativescript-marketplace-demo/blob/master/app/App_Resources/Android/AndroidManifest.xml). In the `manifest` element you will need a permission like:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

If you do not need the actual data, but an image source instead, you can also check the [decodeTumb method here](https://github.com/NativeScript/nativescript-imagepicker/blob/release/source/viewmodel.android.ts#L88) and omit the down sampling to get an image source suitable for presentation with the original size image.

If you plan to upload the image you should be able to shortwire the uri-s here to the [nativescript-background-http's uploadFile](https://www.npmjs.com/package/nativescript-background-http).
