### ISSUE TITLE
Conflict with nativescript-facebook-login

### ISSUE THREAD

**Issue by Denton09** [NativeScript/nativescript-imagepicker#51]
I have nativescript-imagepicker installed, version 2.4.1, and nativescript-facebook-login, version 0.2.0. At first I login with Facebook, then I take the picture. Block of code doesn’t work:
```
.then(function(selection) {
    console.log("Selection done:");
    selection.forEach(function(selected) {
        console.log(" - " + selected.uri);
    });
}).catch(function (e) {
    console.log(e);
});
```
I reviewed source code and found out that the handler `onResult(args)` for event: 
`application.android.on(application.AndroidApplication.activityResultEvent, onResult); `
doesn’t work. That doesn't start.

**Comment by mounirka** [comment]
hi @Denton09 i just read by chance your post. I had got your same problem and i solved it reported it to the author of the facebook login plugin.
Here is the link with the answer: [https://github.com/AntonioCuevaUrraco/nativescript-facebook-login/issues/28](url)
Maybe it's too late for you, but i hope the answer can help others.

**Comment by tsonevn** [comment]
Hi @Denton09,
Do you still have a problem with `nativescript-imagepicker`? As @mounirka suggested, most probably this issue has been related to `nativescript-facebook-login` plugin and there is nothing to do in `imagepicker` plugin.

Regards,
@tsonevn

**Comment by Denton09** [comment]
Yes, thanks. This bug is in the nativescript-facebook-login. The issue is closed.

Regards,
@Denton09
