### ISSUE TITLE
It shows videos on the selection of images (iOS)

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-imagepicker#54]
Obviously gets an error when someone picks them.

The problem is that you might not even distinguish they are images.

To reproduce it, just start this sample app on you iphone with videos: https://github.com/NativeScript/sample-ImageUpload

**Comment by PanayotCankov** [comment]
We should probably add an option to switch between selecting "images", "videos" or "both" type of assets for iOS.

**Comment by Pinny3** [comment]
+1

**Comment by derekm228** [comment]
Definitely a blocker for production deployment.

**Comment by tbozhikov** [comment]
Hi guys, the [latest version](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.0) of the imagepicker plugin now offers `mediaType` option. You can set it accordingly to select what assets you need to select in iOS. Possible options are:
`ImagePickerMediaType.Any`
`ImagePickerMediaType.Image` (default)
`ImagePickerMediaType.Video`
Sample:
```
import * as imagepicker from "nativescript-imagepicker";
import {ImagePickerMediaType} from "nativescript-imagepicker";

imagepicker.create({ mode: "single", mediaType: ImagePickerMediaType.Any })
```
I hope this helps. I am closing this issue now, feel free to reopen it if you have further questions.
