### ISSUE TITLE
Undefined fileUri

### ISSUE THREAD

**Issue by Thabangtg** [NativeScript/nativescript-imagepicker#58]
Hello. 
I just want to thank you for a great example you gave us and it helped me a lot on the project im currently busy with.

However, i seem to have an undefined fileUri when i have selected an image, but i do get the Uri part.

Regards.

**Comment by tsonevn** [comment]
Hi @Thabangtg,

Thank you for your interest in NativeScript.

The returned items from the selected images will be from Assets type, which do not have `fileUri` property. You could use getImage(), which will return imageSource and you could save it on the device with saveToFile(<file_path>, <file_type>). As a result you will be able to use the new created file path. For further help you could review the sample example from [here](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L92-L105).

Let me know, whether this helps.
