### ISSUE TITLE
View model data is lost upon return to view.

### ISSUE THREAD

**Issue by NickArgyle** [NativeScript/nativescript-imagepicker#59]
If you have data on a page, for example in a list view that is tied to an observable array within a view model, or if you have a variable saved within the context of a view, it is removed once the image picker is finished and returns to the primary view. Is there a way to save this data without having to cache it externally and reload it after an image is picked, like the clearHistory value in the NS navigation function?

**Comment by NickArgyle** [comment]
As a visual example, in the first image, the "Sign-Up Sheet" option is selected. After picking an image, the selector has reverted to the default option. 
![img_3650](https://cloud.githubusercontent.com/assets/8006703/21205438/4f9be654-c22a-11e6-8219-3d7e15d84150.PNG)
![img_3651](https://cloud.githubusercontent.com/assets/8006703/21205437/4f9bcfe8-c22a-11e6-8bd2-e38b76e2db1f.PNG)

**Comment by tsonevn** [comment]
Hi @NickArgyle,

I reviewed your problem, however was unable to reproduce this behavior, while using `nativescript-imagepicker `. It could be something related with the project and the time, when the view-model has been created. To save some data, you could use [application-settings](http://docs.nativescript.org/cookbook/application-settings), which could help you to save page state.

Hope this information helps.

**Comment by NickArgyle** [comment]
Interestingly, text is cached, but custom information saved in a view model, such as arrays and other object types which are not supported by application-settings do not persist. As a workaround, I'm caching the data to a sqlite db before loading the image picker, though this adds some overhead.

**Comment by NaokiDaxima** [comment]
Hi @NickArgyle.

I have had a similar issue with the imagepicker and under ios. From my tests android seems ok in maintaining the data, after returning from the imagepicker.

**Comment by 3rror404** [comment]
The page.loaded, page.navigatingTo and page.navigatedTo events will be fired when you return from the image picker. If you create your binding context in any of these events it will be overwritten when the image picker is closed.

Make sure you check if the bindingContext already exists before creating:

```
var page;
var pageData;

exports.onLoaded = function(args) {
    page = args.object;

    if (!page.bindingContext) {
        // Create your binding context here.
        pageData = new Observable()
        page.bindingContext = pageData;
    }
}
```
