### ISSUE TITLE
[question] Picking Video Files

### ISSUE THREAD

**Issue by RyamBaCo** [NativeScript/nativescript-imagepicker#60]
Hey there,

thanks for that awesome plugin! I know it's called _image_ picker, but is there any future support for additionally picking video files planned?

**Comment by tsonevn** [comment]
Hi @RyamBaCo,
Thank you for your interest in `nativescirpt-imagepicker`.
Regards to your question, at the moment there is no plans to provide such a functionality for the plugin.

In case you need such a functionality, you could create your own plugin, which provides functionality to pick video for both Android and iOS, More info about, how to create a plugin, could be found in the below-attached links.
http://docs.nativescript.org/plugins/plugins
http://developer.telerik.com/featured/creating-nativescript-plugins-in-typescript/
http://developer.telerik.com/featured/write-nativescript-plugins-theyre-easier-cordova-plugins/
http://www.nativescriptsnacks.com/videos/2016/09/12/plugin-seed.html

Furthermore, for Android, you could review [nativescript-file-picker](https://www.npmjs.com/package/nativescript-file-picker) and its demo [here](https://github.com/kazemihabib/nativescript-file-picker/tree/master/demo).


Regards,
@tsonevn
