### ISSUE TITLE
Problem in the package.json

### ISSUE THREAD

**Issue by mounirka** [NativeScript/nativescript-imagepicker#61]
Hi guys, i used the plugin for my app targeting android and ios and it works fine for android both when i was debugging and when i published, but for ios during the debug it worked but when i want to publish it didn't pass the verification process and gave the error: Invalid binary.

I had to change the package.json removing dependecy and devDependency and the problem was fixed.
I use nativescript 2.3.0, they told me that in the 2.4.0 version the problem doesn't sussit

**Comment by tsonevn** [comment]
Hi @mounirka, 
Thank you for reporting this issue.

Could you provide some more info about the error, which you receive, when  the verification process didn't pass. It would also help if you give us also info about the dependencies, which you have removed for fixing the problem.

Thank you in advance for your cooperation.
Regards,
@tsonevn

**Comment by mounirka** [comment]
The error was something like:
I changed the package.json in the nativescript-imagepicker plugin like this
Your version:
```
{
  "description": "A plugin for the NativeScript framework implementing multiple image picker",
  "repository": {
    "type": "git",
    "url": "https://github.com/NativeScript/nativescript-imagepicker"
  },
  "name": "nativescript-imagepicker",
  "version": "2.4.1",
  "nativescript": {
    "platforms": {
      "android": "2.4.0",
      "ios": "2.4.0"
    }
  },
  "dependencies": {
    "tns-core-modules": "*",
    "nativescript-telerik-ui": "*"
  },
  "main": "viewmodel.js",
  "devDependencies": {
    "tns-platform-declarations": "next",
    "typescript": "^2.0.3"
  },
  "scripts": {
    "tsc": "tsc",
    "prepublish": "tsc"
  }
}
```

My version:
```
{
  "description": "A plugin for the NativeScript framework implementing multiple image picker",
  "repository": {
    "type": "git",
    "url": "https://github.com/NativeScript/nativescript-imagepicker"
  },
  "name": "nativescript-imagepicker",
  "version": "2.4.1",
  "nativescript": {
    "platforms": {
      "android": "2.4.0",
      "ios": "2.4.0"
    }
  },
  "main": "viewmodel.js",
  "scripts": {
    "tsc": "tsc",
    "prepublish": "tsc"
  }
}
```
I don't know if this the right think to do but for me worked

**Comment by mounirka** [comment]
UPDATE: the app was rejected by the app store because when it can't find the module nativescript-imagepicker
Very strange situation, when i was debugging everything worked fine but now it gives error.

**Comment by mounirka** [comment]
After a long night the only thing that seemed to work was to install the nativescript-telerik-ui plugin in my project and then add the imagepicker plugin:
```
tns plugin add nativescript-telerik-ui
tns plugin add nativescript-imagepicker
```
Doing this way the plugin works when debugging and passed the validation on xcode.
