### ISSUE TITLE
Fix package.json to supporting AoT compilation

### ISSUE THREAD

**Issue by newapx** [NativeScript/nativescript-imagepicker#64]
I try use webpack and after command npm run start-android-bundle got the error: not find module nativescript-imagepicker.

For correct compilation I replace in package.json property main
from "main": "viewmodel.js", to "main": "viewmodel",

More info: https://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#recommendations-for-plugin-authors

**Comment by tsonevn** [comment]
Hi @newapx,

This problem has not be related directly with this plugin. `nativescript-imagepicker` plugin use `nativescript-telerik-ui` and has it as a dependency in its `package.json` file. 

The problem with webpack has been related with UI for NativeScirpt and this issue will be fixed several days after upcoming release of the `nativescript-telerik-ui`.

For further info you could keep track on [this ](https://github.com/NativeScript/nativescript-dev-webpack/issues/31#issuecomment-271838184) issue.

Regards,
@tsonevn
