### ISSUE TITLE
Generate JS or Update NPM

### ISSUE THREAD

**Issue by Daxito** [NativeScript/nativescript-imagepicker#65]
Hi,
I have my App using just JS, and I am having lots of trouble compiling the TS file, can someone release a the most recent version to NPM or regenerate the JS files?

**Comment by Daxito** [comment]
I am trying to manually convert the TS file into JS but I have a couple of issues, all this for iOS:
1. The generated "images" page has this tag:
   < Image height="78" width="78" opacity="{{ selected ? 0.7 : 1 }}" src="{{ $value }}" />
But $value is actually an object, this object has fileUri and if I replace $value with fileUri it works for the simulator, I am able to see the image but it does not work for the real device, no image is displayed

2. The object AssetPH is NOT observable so I get error when selecting an image (from the simulator), the error is related to line:
this.notifyPropertyChange("selected", this.selected);

this.notifyPropertyChange is not a function, because the object never extends an Observable, the weird thing here is that the demo works, but the demo is all TS, my project is all JS.

Any idea?
Thanks!

**Comment by tsonevn** [comment]
Hi @Daxito,
Could you provide more info about your scenario? 

In case you would like to rebuild the plugin, you should first run `npm install`, which will install the needed dependencies and then run `tsc`.

The problem with using fileUri for Image src could be related to the case when you select an image from a cloud. Those images do not have real file Uri and could be caused this behavior.

About the last question, when the asset has been returned for the selected image you should use `getImage()` method, which will return imageSource. For example, review the sample [here](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L92-L105).

Hope this helps

**Comment by Daxito** [comment]
@tsonevn 
Thank you for the answer! I appreciate it.
Since I was stuck with this issue I had to create a new plugin for iOS, I use https://github.com/zhangao0086/DKImagePickerController instead, for Android works great though!
