### ISSUE TITLE
Add Android 6 & 7 runtime permissions [up-for-grabs]

### ISSUE THREAD

**Issue by Sprechen** [NativeScript/nativescript-imagepicker#66]
Hi guys!
It seems that this plugin doesn't support the new Android 6 permission request at runtime (https://developer.android.com/training/permissions/requesting.html).

I tried your example project on my Android phone with Nougat and on the console I found the following stack trace:

Error: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=2702, uid=10196 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
JS:     android.os.Parcel.readException(Parcel.java:1683)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
JS:     android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
JS:     android.content.ContentResolver.query(ContentResolver.java:532)
JS:     android.content.ContentResolver.query(ContentResolver.java:473)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:895)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:879)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:871)
JS:     com.tns.NativeScriptActivity.onActivityResult(android.app.Activity.java)
JS:     android.app.Activity.dispatchActivityResult(Activity.java:6958)
JS:     android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
JS:     android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
JS:     android.app.ActivityThread.-wrap20(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6077)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

The preview of the picked photo is correctly visualized on the app, but I am a bit scared about the reported error!

**Comment by NickIliev** [comment]
@Sprechen thank you for reporting this one - as a workaround try the solution [in this README ](https://github.com/NativeScript/sample-ImageUpload/blob/master/README.md)

**Comment by manoldonev** [comment]
@NickIliev It would be convenient if the imagepicker implements the explicit permissions logic for newer Android versions much like the nativescript-geolocation plugin [here](https://github.com/NativeScript/nativescript-geolocation/blob/master/source/nativescript-geolocation.android.ts)

**Comment by NickIliev** [comment]
@manoldonev sounds like a good feature. Marking this as an enhancement for the plugin
