### ISSUE TITLE
Get image from iCloud on IOS

### ISSUE THREAD

**Issue by mounirka** [NativeScript/nativescript-imagepicker#67]
Hi guys, the plugin is working perfectly on ios if the image that i want is locally saved in the device, but if i choose an image that i saved on my iCloud, the promise return without any data of the image.
Is there a workaround for this? Thank you.

**Comment by tsonevn** [comment]
Hi @mounirka,

For your case, you could use `getImage()` method for the selected item from the Cloud, which will return imageSource. then you should be able to use the image in your project. For further info and sample code, you could review the comment in [this ](https://github.com/NativeScript/nativescript-imagepicker/issues/53#issuecomment-266990852) issue.

Hope this helps.

**Comment by mounirka** [comment]
This is the code that i've been using and it still doesn't work with icloud
```
let context = imagepickerModule.create({
            mode: "single"
        });
        context
            .authorize()
            .then(function() {
                return context.present();
            })
            .then((selection) => {
                selection.forEach((selected) => {
                    selected.getImage().then((img) => {
                      this.cropper.show(img).then((args) => {
                              // Here i show the image to the user
                        })
                        .catch((e) => {
                            console.log("E: " + e.message());
                        });
                    },
                    (error) => {
                      console.log("getImage error", error);
                    }
                  );
                });
            }).catch(function (e) {
                console.log(e);
            });
```

**Comment by tsonevn** [comment]
Hi @mounirka,
I have tested your scenario while using `nativescript-imagepicker` and `nativescript-imagecropper` in a sample app. 
To be able to use an image from a cloud, you should first save the image in a temporary file in the app as it has been shown in my previous comment. This has been related to the fact that, when you access such an image, there is no existing image `Uri` on the device.

When you save the image, you would also be able to use `cropper` `show` method. 
For your convenience, I am attaching most important part of the code.

```
selection.forEach(function(selected_item) {
                selected_item.getImage().then(function(imagesource){
                    let folder = fs.knownFolders.documents();
                    let path = fs.path.join(folder.path, "Test"+counter+".png");
                    let saved = imagesource.saveToFile(path, "png");
                    if(saved){
                        var task = sendImages("Image"+counter+".png", path);
                        var item = new observable.Observable();
                        var cropper = new icModule.ImageCropper();
                        cropper.show(imagesource).then(function(args){
                        console.log(JSON.stringify(args));
                        if(args.image !== null){
                            // _image1.imageSource = args.image;
                                item.set("thumb", args.image);
                                item.set("uri", "Test"+counter+".png");
                                item.set("uploadTask", task);
                        }
                        
                        })

                        imageItems.push(item);
                    }
                    counter++;
                })
                
			});
```

The full project could be found [here](https://github.com/tsonevn/imagePickerCropper).

Hope this helps

**Comment by pap5508** [comment]
@tsonevn : To select PDF and Word file stored on iCloud.. select it and call API..??

Do we have any sample code for that.. I do not need it for Image..
