### ISSUE TITLE
Error: more than one library with package name 'com.telerik.android.data'

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/nativescript-imagepicker#68]
hi , i am trying out this plugin  with Nativesript 2.5 , it builds failed with following exception :  
(i have already tried to delete platforms folder and node_modules folder, npm/tns install =>npm clean =>  add platforms , still not working )

:processF0F1F2DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2DebugResources'.
> Error: more than one library with package name 'com.telerik.android.data'

Thanks

**Comment by tsonevn** [comment]
Hi @c1ngular,

Could you build your project with `tns run <platform_name> --log trace` and to send us the log from the console? It would help if you could you give us the exact steps, which you are using to build your project and also to attached your project `package.json` file.

Regards,
@tsonevn

**Comment by c1ngular** [comment]
@tsonevn
thanks for replying so quickly !
 i am using this plugin with telerik-ui-pro , i removed telerik-ui-pro , using the free version instead , then it is working now [funny]! though while building , it gives a log, "file:///app/tns_modules/tns-core-modules/globals/globals.js:119:20: Border is deprecated", guess it's no big deal !

**Comment by tsonevn** [comment]
Hi @c1ngular,
`Border is deprecated` message is only a warning and should not have any issues while building the project.
