### ISSUE TITLE
Not working with webpack

### ISSUE THREAD

**Issue by bnussey** [NativeScript/nativescript-imagepicker#70]
This plugin doesn't seem to work with ng2 and webpack. I am getting this error whenever trying to init a component with it:

`Module not found: Error: Can't resolve 'nativescript-imagepicker`

**Comment by bnussey** [comment]
Does this relate to https://github.com/NativeScript/nativescript-imagepicker/issues/64 ?

**Comment by tsonevn** [comment]
Hi @bnussey,

At the moment the problem with webpack has been related to UI for NativeScrip and the fact that `nativescript-imagepicker` has it as a dependency. Indeed this issue has been related with [#64](https://github.com/NativeScript/nativescript-imagepicker/issues/64). For further info you could keep track on [the issue](https://github.com/NativeScript/nativescript-dev-webpack/issues/31#issuecomment-271838184) logged in `nativescript-dev-webpack` repo. UI for NativeScript will release new version soon, where this behavior should be fixed.

**Comment by sis0k0** [comment]
A new version of the package (2.5.1) with webpack support has been published. You can use it with the `next` tag of the `nativescript-telerik-ui` plugin.
