### ISSUE TITLE
iOS - create thumb-nail callback not working

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-imagepicker#71]
On iOS, the thumb-nail callback is not being called

`selection.forEach(function(selected_item : imagepickerModule.SelectedAsset )
{
    selected_item.addEventListener( observable.Observable.propertyChangeEvent,
                    function (pcd: observable.PropertyChangeData)
                    {
                        console.log( "*** Thumb image created=" + pcd.eventName + " " + pcd.propertyName + " " + pcd.value);
                    } );

    selected_item.thumb;    // reference - initiates the above event
}`

Any help?

**Comment by tsonevn** [comment]
Hi @erjdriver,
Could you provide some more info about your case and what you are trying to achieve?
You could also review the sample project [here](https://github.com/NativeScript/sample-ImageUpload), where has been used `nativescript-imagepicker` plugin.

**Comment by erjdriver** [comment]
After an image is picked, I'm trying to display a thumb-nail copy of the image of the screen. The problem is that under the ios version, I don't get the thumb-nail-done callback. Works under Android.

`   var context = imagepickerModule.create(
    {
        mode: "single"
    });

    context
        .authorize()
        .then(function()
        {
            return context.present();
        })
        .then(function(selection)
        {
	        selection.forEach(function(selected_item : imagepickerModule.SelectedAsset )
            {
                console.log( "selected=" + selected_item.fileUri );
                
                selected_item.addEventListener( observable.Observable.propertyChangeEvent,
                    function (pcd: observable.PropertyChangeData)
                    {
                        console.log( "*** Thumb image created=" + pcd.eventName + " " + pcd.propertyName + " " + pcd.value);

                        if ( pcd.propertyName == "thumb" )
                        {
                            let img : imageSourceModule.ImageSource = pcd.value;

                            console.log( "thumb img=" + img.width + "x" + img.height );
                        }
                    } );

                selected_item.thumb;    // reference - initiates the above event

            } );
        }).catch(function (e)
        {
            console.error( "ERROR " + e.message );
        });`

**Comment by tsonevn** [comment]
Hi @erjdriver ,

The `thumb` has been returned in different time for both platforms. In `Android`, this property will be returned synchronically, however, for `iOS`  the thumb will be returned async. For your case, you should use `getImage()` method instead of `addEventListener`, which will be fired when the image is available.  This will allow you also to use an image, which has been available on `cloud`. For your convenience, I am attaching sample code.

XML
```
<Image width="100" height="100" src="{{imagesource}}" stretch ="none" />
```

JavaScript
```
selection.forEach(function(selected_item) {
                selected_item.getImage().then(function(imagesource){
                    
                        mainViewModel.set("imagesource",selected_item.thumb);
                        })

                    }
                })
                
			});
```

Hope this helps.
