### ISSUE TITLE
select image controls are not showing on iOS

### ISSUE THREAD

**Issue by cutout33** [NativeScript/nativescript-imagepicker#72]
Hi,

Am using this on iOS 10.2 and ins 2.5. it works great on android but on iOS it's not showing any controls  to select images. I mean I can see the images and albums and on selecting one image the image is highlighted but selected promise is not returned! this is on emulator and device. I use code from your examples and it's for single selection of images.
I noticed the following message in the logs:

```
CONSOLE LOG file:///app/tns_modules/tns-core-modules/globals/globals.js:119:20: UIImagePickerControllerDelegateImpl is deprecated
CONSOLE LOG file:///app/tns_modules/tns-core-modules/globals/globals.js:119:20: UIImagePickerControllerDelegateImpl is deprecated
```

Also check attached

<img width="384" alt="screen shot 2017-02-18 at 8 18 52 am" src="https://cloud.githubusercontent.com/assets/1323757/23091184/9e0b00ec-f5b8-11e6-8ee3-839a1acfef05.png">

**Comment by tsonevn** [comment]
Hi @cutout33, 
If I understand you correctly, you have an issue with receiving the data for the selected images. 
I have tested the case with `sample-ImageUpload` project and it seems to work as expected on iOS.
Could you review the sample app [here](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L93-L123) and verify, whether you will have the same problem.
You could also verify, whether you are using the latest version `2.5.1` of `nativescript-imagepicker` plugin.

**Comment by cutout33** [comment]
Thank you for the response. I just found out the I've used the following code in my app which caused the problem:

```javascript
var frameModule = require("ui/frame");
frameModule.topmost().ios.navBarVisibility = "never";
```

Thanks
