### ISSUE TITLE
[Generic] Creating an image format with an unknown type is an error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-imagepicker#75]
_From @pap5508 on February 24, 2017 9:51_

Select Photo from the Gallery iOS Simulator.

Error : 
 
`[Generic] Creating an image format with an unknown type is an error
*** ASL MESSAGE SIZE (25813666 bytes) EXCEEDED MAXIMIMUM SIZE (8192000 bytes) *** `

Package.json

`"nativescript-imagepicker": "^2.5.1",`

_Copied from original issue: NativeScript/nativescript-angular#681_

**Comment by tsonevn** [comment]
Hi @pap5508,
Could you provide some more info about your case? It would help if you could give us some code snippets or sample project, which will allow us to recreate the prblem. 

In the meantime, you could also review the sample project [here ](https://github.com/NativeScript/sample-ImageUpload) and to verify, whether you will have the same problem.

**Comment by pap5508** [comment]
@tsonevn : this situation is occurred while photo size is too large and converting it into base64 

Will share with you screenshot and Program to regenerate the Error.

**Comment by tsonevn** [comment]
Hi @pap5508, 

I tested again [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) app while using a large image, however, I am still unable to reproduce this behavior.

Regarding that converting the imageSource to base64 string will not work at the moment. For further info, you could keep track on the issue [here](https://github.com/NativeScript/NativeScript/issues/3605).

NativeScript you could use ImageSource `saveToFile` method, which allows you to save the image source in a temporary file with the needed quality. For more info review the API Reference [here](http://docs.nativescript.org/api-reference/classes/_image_source_.imagesource.html#savetofile).

**Comment by slasho** [comment]
the quality option doesn't work... in a file of 1mb when savetofile(path,"jpg",10) it produces an 3MB file
