### ISSUE TITLE
Issue with getImageData on Android

### ISSUE THREAD

**Issue by NaokiDaxima** [NativeScript/nativescript-imagepicker#77]
Hi,

I am having some issues with the "getImageData" function and the ArrayBuffer that is returned. It appears as if the data is not correctly saved into the ArrayBuffer. This is for android only, iOS is working fine. Is anyone else having issues with using "getImageData"?

I am working on code that takes the arraybuffer and splits it up into smaller chuncks for data transmission (after base64 encoding). I did some tests on the "getByteBuffer" function inside the "nativescript-imagepicker/viewmodel.android.ts", and it appears as if some of the data was getting cutoff in the "buffer" variable. 

As a temporary work around I created a similar function, but had it return a byte array.

Thanks

Platform::
Android

NativeScript:
2.4.1

**Comment by tsonevn** [comment]
Hi @NaokiDaxima, 

Could you provide some more info about the problem and what you are trying to achieve? 
It would also help if you could provide sample project, where the problem could be reproduced and debugged locally.
Regarding that, you could review [nativescript-background-http](https://github.com/NativeScript/nativescript-background-http) plugin and whether it is applicable for you.

**Comment by NaokiDaxima** [comment]
Hi,

I am working on a function for uploading for images from camera gallery or camera to a server through web.api calls. The api expects the data as base64 encoded byte arrays and data is transmitted in 1MiB chunks. So basically:

Read File Contents -> Split in to byte array chunks -> convert to base64 -> upload through http request.

On iOS, I was able to call the "getImageData()" to get the data of the image as a ArrayBuffer. Split it up into 1MiB chunks with ArraryBuffer.slice and then encode and transmit. However on android, the image transmitted is not correct and cannot be opened.

I am not able to post the full code, but the portion below is my testing of reading a text file, and trying to compare the final base64 output. Thanks 

    var app = require("application");
    var platform = require("platform");
    var appSettings = require("application-settings");
    var fs = require("file-system");
    var cryptoJS = require("nativescript-toolbox/crypto-js");


    function getArrayBufferFromFile(filePath){
        var fileURI;
        var file = new java.io.File(filePath);
        if(platform.device.sdkVersion >= 23){
            // NEW
            fileURI = (android.support.v4.content).FileProvider.getUriForFile(app.android.currentContext, app.android.nativeApp.getPackageName() + ".provider", file);
            // NEW
        } else {
            fileURI = android.net.Uri.fromFile(file);
        }

        var bb = getByteBuffer(fileURI);
        var ab = ArrayBuffer.from(bb);

        var wa = cryptoJS.lib.WordArray.create(ab);
        var parsedStr = cryptoJS.enc.Base64.stringify(wa);
        console.log(parsedStr);

        return ab;
    }

    function getByteBuffer(uri) {
        var file = null; // android.content.res.AssetFileDescriptor = null;
        try {
            file = getContentResolver().openAssetFileDescriptor(uri, "r");

            // Determine how many bytes to allocate in memory based on the file length
            var length = file.getLength();
            console.log("length1:" + length);
            var buffer = new java.nio.ByteBuffer.allocateDirect(length);
            var bytes = buffer.array();
            console.log("lenth2:" + bytes.length);
            var stream = file.createInputStream();

            // Buffer the data in 4KiB amounts
            var reader = new java.io.BufferedInputStream(stream, 4096);
            reader.read(bytes, 0, bytes.length);
            
            return buffer;
        } finally {
            if (file) {
                file.close();
            }
        }
    }
    // returns: android.content.ContentResolver
    function getContentResolver()  {
        return app.android.nativeApp.getContentResolver();
    }

Input text file contents: hellworld
Expected Output: aGVsbG93b3JsZA==
Output: b3dvcmxkAAAAAA==

**Comment by radeva** [comment]
Hi @NaokiDaxima ,

Is this issue still valid or you managed to solve it?

**Comment by jujupec** [comment]
@NickIliev I use the plugin tns-platform-declarations (v3.4.1) for getting this library but I don't find the FileProvider class and its methods in the file node_modules/tns-platform-declarations/android/android17.d.ts.

I fixed it by typing the right code for the class FileProvider in the file android17.d.ts in node module:

> export class  FileProvider extends java.lang.Class<android.content.ContentProvider>{
> 					constructor();
> 					public static getUriForFile(context: android.content.Context, authority: string, file: java.io.File)
> 				}

But if you have a better solution...
