### ISSUE TITLE
Image Selection Error when selecting from Google Drive on Android Device

### ISSUE THREAD

**Issue by vagabond92** [NativeScript/nativescript-imagepicker#78]
The plugin fails to retrieve an image when selecting from Google Drive. 

Android 6.0.1

Steps to reproduce:
1. Start image picker in app.
2. In drop down select Open from Google drive.
3. select image.

No image is selected. 

In my application I check the fileUri of the selected image. This property is not defined for the selectedAsset.

I have debugged to the following point: 

The length of selection is 1. However, the values in selected are set to the following:

 {"_observers":{},"disableNotifications":{},"_uri":{},"_thumbRequested":false}

When I try to access: selected.getImage()  or selected.fileUri the application crashes with TypeError: Cannot read property of undefined.

This only happens when attempting to access images stored in Google Drive on the device.

Any help would be greatly appreciated.

My suspicion is that Google Drive is returning a promise for the underlying asset, rather than the actual asset. But I don't know enough to really dig around and figure it out.

**Comment by tsonevn** [comment]
Hi @vagabond92, 

Could you provide some code snippets or sample project, which could be debugged locally?

In the meantime, you could verify, whether you will have the same behavior while using [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) app.

Regards,
@tsonevn

**Comment by vagabond92** [comment]
The sample-ImageUpload app has the same problem, though it's not as much of a problem. Log is below:


03-14 06:36:44.714 10929 11002 V GoogleSignatureVerifier: dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
JS: Permissions granted!
JS: currentBytes: 4096
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: 720896
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: 983040
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: 1310720
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: undefined
JS: totalBytes: undefined
JS: eventName: error
JS: Permissions granted!
JS: currentBytes: 4096
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: 720896
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: 983040
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: 1376256
JS: totalBytes: 1493564
JS: eventName: progress
JS: currentBytes: undefined
JS: totalBytes: undefined
JS: eventName: error
JS: Permissions granted!
JS: currentBytes: 4096
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 720896
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 983040
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 1507328
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 2228224
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 2686976
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 3801088
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 4653056
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 5963776
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 7274496
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 8650752
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 9633792
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 10289152
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: 11141120
JS: totalBytes: 11438035
JS: eventName: progress
JS: currentBytes: undefined
JS: totalBytes: undefined
JS: eventName: error

It appears that google drive returns a promise to the asset, rather than the asset itself. It tries to upload, but the image is undefined. The screen goes black for a while, then it uploads the file. Then after I have uploaded four pictures the sample-ImageUpload app crashes with the following stack trace:

An uncaught Exception occurred on "pool-7-thread-1" thread.
java.lang.OutOfMemoryError: Failed to allocate a 12887681 byte allocation with 12606376 free bytes and 12MB until OOM
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
	at net.gotev.uploadservice.http.impl.HurlStackConnection.getResponseBodyAsByteArray(HurlStackConnection.java:128)
	at net.gotev.uploadservice.http.impl.HurlStackConnection.getServerResponseBody(HurlStackConnection.java:103)
	at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:83)
	at net.gotev.uploadservice.UploadTask.run(UploadTask.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

I suspect this OOM error is related to the android image OOM errors that occur in other contexts (this thread for example https://github.com/NativeScript/NativeScript/issues/2571 though there are others).

Moral of story: there's something broken when accessing images from Google Drive. I'm writing my application to handle the error with a message that accessing GD is not permitted at this time, but that's not a good solution.

Sorry I don't have the time or the knowledge to debug better than this.

**Comment by tsonevn** [comment]
Hi @vagabond92 ,
This error has been related to an issue with Image component and recycling the native view. This has been already reported [here](https://github.com/NativeScript/NativeScript/issues/3153). For further info, you could keep track on the issue.

In the meantime, you could use [nativescript-fresco](https://github.com/NativeScript/nativescript-fresco) in Android, which will resolve this behavior at the moment.

**Comment by vagabond92** [comment]
Hi @tsonevn, yes, the OOM error is related to 

https://github.com/NativeScript/NativeScript/issues/3153

however, the issue of accessing images from google drive is a separate issue. I just happened to notice the OOM error crops up when accessing images on google drive. This means that how images are accessed by the imagepicker is different when accessing GD images, compared to the native storage. When I access images on local storage, I don't run into the OOM error. 

nativescript-fresco won't solve THIS issue, which is that 

Moral of story: this bug still remains. Accessing images on Google Drive breaks code that tries to access selected_item.fileUri.

You can check this by inserting: 
                console.log('DEBUG::' + selected_item.fileUri)
after the line: 
			selection.forEach(function(selected_item) {
in the function startSelection(context) of main-page.js in the sample-ImageUpload app.

When selecting an image from the device, it will return a valid path:
      DEBUG::/storage/emulated/0/DCIM/Camera/20170301_153932.jpg
However, when accessing an image on GoogleDrive:
     DEBUG::undefined

It seems to me that this is incorrect behavior for the imagepicker, and the bug I am trying to document here.

**Comment by tsonevn** [comment]
Hi @vagabond92,
While selecting an image from the cloud at the very first moment it does not exist on the device and indeed the returned fileUri will be `undefined`. This is something expected. 

To be able to use those images you should use `getImage` method, which will return an imageSource of the selected image from drive, You should also make local copy of the image while using ImageSource `save` method.

This scenario has been shown in the [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) app. I am also attaching the sample code snippet from the project.

```
selected_item.getImage().then(function(imagesource){
                    console.log('DEBUG::' + selected_item.fileUri);
                    let folder = fs.knownFolders.documents();
                    let path = fs.path.join(folder.path, "Test"+counter+".png");
                    let saved = imagesource.saveToFile(path, "png");
                    
                    if(saved){
                        var task = sendImages("Image"+counter+".png", path);
                        var item = new observable.Observable();
                        item.set("thumb", imagesource);
                        item.set("uri", "Test"+counter+".png");
                        item.set("uploadTask", task);

                        imageItems.push(item);
                    }
                    counter++;
                })
```

**Comment by StefhanJonas** [comment]
Anyone having luck with getting images from Google Drive with the latest version (6.0.1)? The getImage function is not present anymore, and assets from Google Drive / Dropbox are "empty". I've tried saving images using [this](https://docs.nativescript.org/cookbook/image-source#save-image-from-image-asset-to-png-file) approach (which just gives the error: "Uncaught (in promise): Asset '' cannot be found"). Also tried [getImageAsync](https://docs.nativescript.org/api-reference/classes/_image_asset_.imageasset#getimageasync) which just returns null.
