### ISSUE TITLE
Opening image picker from within modal

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/nativescript-imagepicker#79]
When the image picker is triggered from within a page that was opened using `showModal()`, the picker is loaded _behind_ the page. Is there any way to work around this?

**Comment by hiddencaliber** [comment]
Is there any update on this ?

**Comment by moritzvieli** [comment]
That's an iOS-only problem. I am also looking forward to a fix. I just implemented a very ugly workaround for iOS:
1. Before showing the select image dialog, close the modal with an own result code
2. Show the image dialog
3. After selection, save the image on the parent page
4. Display the modal again with the selected image

To show the modal the second time, a timeout is needed, because we cannot display the modal inside the close modal function (the modal is still open):
`            if(values.result == 'pickImage') {
                this.imagePickerProvider.selectPicture()
                .then((response) => {
                    this.newWallPostImage = response.toBase64String('jpeg');
                    this.newWallPost = values.text;

                    // Use a timeout, because opening the modal from here does not work
                    // --> Still open. Timeout of 1 ms did not work on a real device. Maybe
                    // On slower devices, we need to further increase this timeout...
                    setTimeout(() => {
                        // Show the modal again this time containing the image
                        this.editWallPost();
                    }, 500);
                });`

**Comment by moritzvieli** [comment]
Welp, just saw the same problem here: https://github.com/NativeScript/NativeScript/issues/3195

And surprisingly, the workaround is exactly the same as mine. Although in my opinion, the timeout is a little wobbly...

Anyway, if Issue 3195 cannot be resolved, it maybe makes sense to handle this case like shown. But NativeScript could make it easier for us and handle this case automatically on iOS.

**Comment by mhmo91** [comment]
Can someone show an example here with Angular, it's not working for me on the IOS

**Comment by FranciZ** [comment]
As far as I can tell this has not been solved for Angular. Simply passing in the `Page` reference does not work.

**Comment by mhmo91** [comment]
@tbozhikov i haven't really got a chance to try the workout, i had to the change the structure n depend on routing instead of modals, would be nice if someone can see this solved though.. ))

**Comment by wendt88** [comment]
for everyone using `nativescript-vue`, I this works for me:
```
let modalView;
if (this.$modal) {
    let view = this.$el;
    // loop until last parentNode, if component is nested in modal
    // otherwise this.$el.nativeView;
    while (view.parentNode) {
         view = view.parentNode;
    }
    modalView = view.nativeView;
}
imagepicker.create({}, modalView);
```

**Comment by abhayastudios** [comment]
@mailiam @tbozhikov

Even with the latest version of this plugin, I am still not able to open the ImagePicker in an existing modal. Here is my example [project](https://github.com/abhayastudios/image-picker-issue79 that:

- opens a modal
- gets a reference from that Page (though `ViewChild`, but also tried through `shownModally` event)
- pass this reference to ImagePicker create

It does open the ImagePicker but it will open an new modal on top of the existing one.

Any ideas?

**Comment by iosdeveloper1001** [comment]
I was facing the same issue with the error of window hierarchy, I Solved it by just adding a Timeout of 10 milliseconds.

```
let context = imagepicker.create({ mode: "single" });
this.startSelection(context);
```

```
public startSelection(context) {
		let _that = this;
		setTimeout(function() {
		context
			.authorize()
			.then(() => {
				return context.present();
			})
			.then((selection) => {
				selection.forEach(function (selected) {
					let source = new ImageSourceModule.ImageSource();
					if (source && source !== null) {
						source.fromAsset(selected).then((source) => {
						}, error => { });
					}
				});
			}).catch(function (e) {
				console.log(e);
			});
		}, 10);
	} 
```
