### ISSUE TITLE
Invalid URI 

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/nativescript-imagepicker#8]
I am trying to ```console.log(selected.fileUri)``` as in the example, however this results in an ```Invalid URI``` error in the console. I am running on Android. Below is the code I am using. 

The full error: ```Error: java.lang.IllegalArgumentException: Invalid URI: context://media/external/images/media/1072602```

```
exports.pickImages = function(){
	var context = imagepicker.create({
		mode: "single"
	});
	
	context
		.authorize()
		.then(function() {
			return context.present();
		})
		.then(function(selection) {
			selection.forEach(function(selected) {
				console.log(selected.fileUri);
			});
		}).catch(function (e) {
			console.log(e);
		});
}
```

**Comment by Daxito** [comment]
+1
I am getting this error too, any clue?

**Comment by mikeres0** [comment]
@Daxito I'll run a test on iOS when I can to see if I get the same error message

**Comment by Stavanger402** [comment]
+1 
I get the same error message on iOS as @Daxito 
Error: Failed to load Page from entry.moduleName: ./tns_modules/imagepicker/albums

**Comment by PanayotCankov** [comment]
This should be fine with v0.0.4 could you give it a try?

**Comment by Nixon1979** [comment]
Nope this issue still persists with V0.0.4
