### ISSUE TITLE
Album preview images don't display on iOS

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/nativescript-imagepicker#80]
The simulator doesn't throw any errors but I see the following when testing on an actual device:

```
CONSOLE LOG file:///app/tns_modules/nativescript-imagepicker/viewmodel.js:313:28: Ignored result: <PHCollectionList: 0x17017fbc0> 1DB0A9D3-8279-4259-91AC-67BAAEA1F6C7/L0/020, title:"iPhoto Events", subtitle:"(null)" collectionListType=2/100
CONSOLE LOG file:///app/tns_modules/nativescript-imagepicker/viewmodel.js:313:28: Ignored result: <PHCollectionList: 0x174177d00> BDCB00E0-3FA1-4682-826C-3AF6D6671300/L0/020, title:"iPhoto Events", subtitle:"(null)" collectionListType=2/100
```

![ns-image-picker-01](https://cloud.githubusercontent.com/assets/1102402/24085630/1d3dc656-0cf7-11e7-996c-88856be911fe.jpg)

I see this behaviour in the [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) and my own app.

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.5.2           │ 2.5.2          │ Up to date    │
│ tns-core-modules │ 2.5.1           │ 2.5.1          │ Up to date    │
│ tns-android      │                 │ 2.5.0          │ Not installed │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by tsonevn** [comment]
Hi @3rror404,

Could you provide some more info about the issue and steps, which could be used for reproducing this scenario? It would also help if you could provide some more info about the device.

I tested the project on a real iOS device, however, was unable to recreate this case.
Regarding that, the message in the console seems to be only a warning and the project should work as expected.

**Comment by 3rror404** [comment]
Hi @tsonevn,
Sorry for the late reply. There aren't really any steps to reproduce. This happens in the [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) with out any changes made.

**Comment by 3rror404** [comment]
I think the issue is this line in viewmodel.ios.ts:

```
if (!this._setThumb && !imagePicker) {
```

Should be:

```
if (!this._setThumb && imagePicker) {
```

**Comment by Johnny1102** [comment]
I have the same problem. Do you know how to fix it?

**Comment by 3rror404** [comment]
@Johnny1102  You need to make the change mentioned in my previous comment. You will have to clone the repo, make the change in `viewmodel.ios.ts` then install your local version of the plugin instead of the npm version.
