### ISSUE TITLE
Support for Nativescript 3.0?

### ISSUE THREAD

**Issue by spmamidi** [NativeScript/nativescript-imagepicker#84]
Support for Nativescript 3.0?

**Comment by tsonevn** [comment]
Hi @spmamidi,
`nativescript-imagepicker` plugin has been already migrated to @rc in the repository, however, it is still not published in `npm`.
In case you want to test it on your side, you could generate `tgz` file locally on your side and use it in the plugin.
For further help and instruction how to do that review the comment [here](https://github.com/NativeScript/nativescript-imagepicker/issues/83#issuecomment-296675736).
