### ISSUE TITLE
{N} 3.0 support

### ISSUE THREAD

**Issue by davecoffin** [NativeScript/nativescript-imagepicker#85]
Is this plugin compatible?

**Comment by tsonevn** [comment]
Hi @davecoffin,
`nativescript-imagepicker` `3.0.1` plugin is fully compatible with NativeScript `3.0`. 
For your convenience, I am attaching a link to [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload) application, which I used for testing.

Let me know, whether I could assist you further

**Comment by davecoffin** [comment]
@tsonevn Thanks!!
