### ISSUE TITLE
[BUG] ImageSource savetoFile always return error because of a string.

### ISSUE THREAD

**Issue by agylmaxlach** [NativeScript/nativescript-imagepicker#88]
Since the update to NativeScript 3.0 I always receive a error with the image-source :

import { ImageAsset }       from 'image-asset';
import imageSource =        require('image-source');

imageSource.saveToFile(path, ImageFormat.jpeg);

**error TS2345: Argument of type 'string' is not assignable to parameter of type '"png" | "jpeg" | "jpg"'.**

**Comment by tsonevn** [comment]
Hi @agylmaxlach,
Thank you for reporting this issue.
I tested this case while using NativeScirpt 3.0, however, was unable to reproduce this case on my side.
Could you verify, whether you added ImageFormat module properly in the project? For example:
```
import {ImageFormat} from "tns-core-modules/ui/enums/enums";
```
For your convenience, I am attaching a sample project.You could review it and make the needed changes, which will allow us to debug this locally.
[Archive.zip](https://github.com/NativeScript/nativescript-imagepicker/files/1018451/Archive.zip)

**Comment by zcqiand** [comment]
i Later, how to solve this problem, I also encountered the same problem

**Comment by tsonevn** [comment]
Hi @zcqiand,
Could you verify whether you have imported properly `ImageFormat`?
```
import {ImageFormat} from "tns-core-modules/ui/enums/enums";
```
I tested this scenario on my side and it seems to work as expected. It would help if you could provide some info about your environment (NativeScript CLI, modules, node versions) and whether you are using NativeScirpt Angular 2 or NativeScript TypeScritp template. Any code snippets or sample project will be appreciated. 
For your convenience, I am attaching my sample project.

[Archive.zip](https://github.com/NativeScript/nativescript-imagepicker/files/1141687/Archive.zip)
