### ISSUE TITLE
The plugin is not working for IOS

### ISSUE THREAD

**Issue by poisytu** [NativeScript/nativescript-imagepicker#9]
The plugin (and the example) work fine for android, but doesn`t show the photos in IOS.

**Comment by mikeres0** [comment]
@poisytu do you get any error messages?

**Comment by poisytu** [comment]
No,just it doesnt open the photos i tried to debug but it seems okay...do you have a working example for ios?

**Comment by PanayotCankov** [comment]
This should be fixed in iOS with v0.0.4. Could you give it a try?

**Comment by poisytu** [comment]
I am working on telerik platform, will you update it there soon :) thank you
