### ISSUE TITLE
Translations for Cancel / Done Buttons on iOS

### ISSUE THREAD

**Issue by RyamBaCo** [NativeScript/nativescript-imagepicker#91]
Hey there,

I'm developing an App with German as primary language. When launching the App on an iPhone with German language settings I couldn't find a possibility to translate the Cancel and Done texts for the buttons. I added the German translation key to CFBundleLocalizations and also set the CFBundleDevelopmentRegion to German in the Info.plist file.

Am I missing something?

**Comment by tsonevn** [comment]
Hi @RyamBaCo,
The ImagePicker Gallery is implemented manually in the plugin and does not support multiple languages at this time. 
For your case you could change the needed strings for the buttons and titles in the image-picker and to create your own tgz file, which you could install in the project. You could follow the below attached steps:

1. `git clone https://github.com/NativeScript/nativescript-imagepicker`
2. `cd nativescript-imagepicker/nativescript-imagepicker`
3. open `nativescript-imagepicker/nativescript-imagepicker/viewmodel.ios.ts` file and make the needed changes for the properties getters.
4. to build the `tgz`, first run `npm install`
5. `tns`
6. `npm pack` - this will generate `tgz` file in the default folder

When you complete that, you could install the plugin from the tgz with `tns plugin add <path to the tgz>`

**Comment by RyamBaCo** [comment]
Alright,

thank you for the detailed response! I will do that and maybe create a pull request where you can add alternative strings as options.

**Comment by RyamBaCo** [comment]
Pull request created.
