### ISSUE TITLE
Cannot build iOS starter kit app with image picker and nativescript-telerik-ui ^3.0.0

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/nativescript-imagepicker#97]
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.1.1           │ 3.1.1          │ Up to date    │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date    │
│ tns-android      │                 │ 3.1.1          │ Not installed │
│ tns-ios          │                 │ 3.1.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

https://github.com/NativeScript/template-master-detail-ng starter kit template is already updated to latest **tns-core-modules**(~3.1.0) and **nativescript-telerik-ui** (^3.0.0)

Steps to reproduce:
1. `tns create master-detail-ng --template https://github.com/NativeScript/template-master-detail-ng --appid org.nativescript.masterdetail`

Due to nativescript-imagepicker still referencing nativescript-telerik-ui version ^2.0.0 we get:
```
UNMET PEER DEPENDENCY nativescript-telerik-ui@3.0.1
```
2. `cd master-detail-ng`
3. `tns run ios`

This errors out with:
```
Searching for devices...
Executing before-liveSync hook from /Users/mdonev/work/master-detail-ng/hooks/before-liveSync/nativescript-angular-sync.js
Copying template files...
  ◡ Installing tns-iosInstalling  tns-ios
  ◟ Installing tns-ios/Users/mdonev/work/master-detail-ng
├── UNMET PEER DEPENDENCY nativescript-telerik-ui@3.0.1
└── tns-ios@3.1.0 

Unable to apply changes on device: AC2BE737-21F1-4775-BB76-DAE73CB76854. Error is: cp: no such file or directory: /Users/mdonev/work/master-detail-ng/node_modules/nativescript-telerik-ui/framework/*.
```

If I manually tweak the imagepicker dependencies to reference nativescript-telerik-ui ^3.0.0 the app seems to work as expected.

**Comment by zbranzov** [comment]
I'm closing this based on PR https://github.com/NativeScript/nativescript-imagepicker/pull/98
